import { ref, reactive } from "vue";
// 로그인 테스트 유저
export const dummyUsers = [
  {
    email: "A@A.com",
    password: "1234",
    name: "김효빈",
    role: "customer", // 꼭 일치하게
    phone: "010-0000-0000",
    address: "서울시",
    detailAddress: "상세주소",
    createdAt: "2025-05-01",
  },
];
export const detailList = [
  {
    id: 1,
    customer: {
      name: "고윤정",
      mobile: "010-2931-8424",
      email: "yunjung@naver.com",
      address: "대구 달서구 대명천로 245",
    },
    membership: {
      name: "호시자키",
      package: "6회권",
      date: "2025-03-17 ~",
      count: "2회 / 6회",
      during: "3개월",
    },
    worker: {
      star: "4.5점(9개 리뷰)",
      name: "박진만",
      mobile: "010-5838-0471",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: "기타 문의",
      title: "라벨 증정",
      memo: "라벨 안 주고 가셨어요 ㅠㅠ",
      file: null,
    },
    reservinfo: {
      type: "비정기 청소",
      machine: "[호시자키] 250kg 이상 1대",
      address: "대구 서구 서대구로 152, 원진빌딩 1층 (평리동 1094-6)",
      date: "2025-05-15, 10:00",
      plus: "자가점검키트",
      memo: "레포트 문자로 보내주세요",
    },
    payment: {
      service: 210000,
      extra: 4900,
      coupon: 0,
      membershipDiscount: -210000,
      extraDiscount: -4900,
      get total() {
        return (
          this.service +
          this.extra +
          this.coupon +
          this.membershipDiscount +
          this.extraDiscount
        );
      },
    },
  },
  {
    id: 3,
    customer: {
      name: "김유인",
      mobile: "010-4922-8744",
      email: "youin@naver.com",
      address: "대구 달서구 미리샘길 32 2층",
    },
    membership: {
      name: null,
      date: null,
      count: null,
      during: null,
    },
    worker: {
      star: "4.5점(9개 리뷰)",
      name: "이용국",
      mobile: "010-1751-4307",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "687632-29-034816",
      during: "1개월",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "일회성 청소",
      machine: "[스탠다드] 50kg 미만 1대",
      address: "대구 북구 태전동 1073-1",
      date: "2025-05-22, 오후 2시",
      plus: "자가 점검 키트",
      memo: null,
    },
    payment: {
      service: 99000,
      extra: 4900,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
      get total() {
        return (
          this.service +
          this.extra +
          this.coupon +
          this.membershipDiscount +
          this.extraDiscount
        );
      },
    },
  },
  {
    id: 2,
    customer: {
      name: "임창민",
      mobile: "010-8733-8264",
      email: "chanmin@naver.com",
      address: "대구 달서구 진천로2길 32-1",
    },
    membership: {
      name: null,
      date: null,
      count: null,
      during: null,
    },
    worker: {
      star: "4.5점(9개 리뷰)",
      name: "이성우",
      mobile: "010-4075-5861",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "농협은행",
      account: "624231-74-982816",
      during: "10개월",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "일회성 청소",
      machine: "[스탠다드] 50kg 미만 1대",
      address: "대구 수성구 동대구로14길 15-6, 1층",
      date: "2025-05-22, 오후 2시",
      plus: null,
      memo: null,
    },
    payment: {
      service: 99000,
      extra: 0,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
      get total() {
        return (
          this.service +
          this.extra +
          this.coupon +
          this.membershipDiscount +
          this.extraDiscount
        );
      },
    },
  },
];
// 예약 내역 데이터
export const reservList = ref([
  {
    id: 1,
    number: "BING-2025-001",
    status: "confirmed",
    date: "2025-03-18, 10:30",
    memo: "라벨 부착해주세요.",
    price: 0,
    reservdate: "2025.03.17(월) 14:00",
  },
  {
    id: 2,
    number: "BING-2025-002",
    status: "assigned",
    date: "2025-05-15, 11:30",
    memo: "레포트 문자로 보내주세요",
    price: 0,
    reservdate: "2025.04.30(수) 16:00",
  },

  {
    id: 3,
    number: "BING-2025-003",
    status: "waiting",
    date: "2025-06-18, 12:00",
    memo: "세제 신청했어요 ~ ^^",
    price: 0,
    reservdate: "2025.06.17(화) 14:00",
  },
]);
// 전체 테이블 데이터
export const fullReservationList = reactive([
  {
    id: 1,
    number: "BING-2025-001",
    status: "confirmed",
    date: "2025-03-18, 14:00",
    memo: "라벨 부착해주세요.",
    price: 0,
    reservdate: "2025.03.17(월) 17:00",
    customer: {
      name: "고윤정",
      mobile: "010-2931-8424",
      email: "yunjung@naver.com",
      address: "대구 서구 달성공원로 15-1, 2층 (비산동 156-10)",
      shop: "business",
    },
    membership: {
      name: "호시자키",
      package: "6회권",
      date: "2025-03-17 ~",
      count: "2회 / 6회",
      during: "3개월",
    },
    worker: {
      bingnb: "bing01",
      star: "4.5점(9개 리뷰)",
      name: "최수빈",
      mobile: "010-4074-1451",
      email: "mrkim@bingfree.co.kr",
      gender: "female",
      health: false,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "563352-09-422616",
      during: "3개월",
    },
    inquiry: {
      type: "기타 문의",
      title: "라벨 증정",
      memo: "라벨 안 주고 가셨어요 ㅠㅠ",
      file: null,
    },
    reservinfo: {
      type: "비정기 청소",
      machine: "[호시자키] 250kg 이상 1대",
      address: "대구 동구 팔공로70길 2",
      date: "2025.05.30",
      time: "10:00",
      plus: "자가점검키트",
      memo: "레포트 문자로 보내주세요",
    },
    payment: {
      service: 210000,
      extra: 4900,
      coupon: 0,
      membershipDiscount: -210000,
      extraDiscount: -4900,
    },
    sh: {
      webid: "qortjf325",
      address: "대구광역시 동구",
      price: 96000,
      joindate: "2025-06-05",
    },
    primemember: true,
  },
  {
    id: 2,
    number: "BING-2025-002",
    status: "waiting",
    date: "2025-06-18, 14:00",
    memo: "세제 신청했어요 ~ ^^",
    price: 0,
    reservdate: "2025.06.17(화) 14:00",
    customer: {
      name: "이나정",
      mobile: "010-6445-0535",
      email: "najeong@naver.com",
      address: "대구 서구 서대구로 152, 원진빌딩 1층 (평리동 1094-6)",
      shop: "personal",
    },
    membership: {
      name: null,
      date: null,
      count: null,
      during: null,
    },
    worker: {
      bingnb: "bing02",
      star: "4.5점(9개 리뷰)",
      name: "김민호",
      mobile: "010-3667-2545",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "843002-14-412814",
      during: "8개월",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "일회성 청소",
      machine: "[디럭스] 100~200kg 1대",
      address: "대구 수성구 들안로 192-5",
      date: "2025.05.31",
      time: "11:00",
      plus: "자가 점검 키트",
      memo: null,
    },
    payment: {
      service: 150000,
      extra: 4900,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
    },
    sh: {
      webid: "tngus325",
      address: "대구광역시 중구",
      price: 106000,
      joindate: "2025-06-05",
    },
    primemember: false,
  },
  {
    id: 3,
    number: "BING-2025-003",
    status: "assigned",
    date: "2025-05-15, 14:00",
    memo: "레포트 문자로 보내주세요",
    price: 0,
    reservdate: "2025.04.30(수) 16:00",
    customer: {
      name: "유하나",
      mobile: "010-3912-0448",
      email: "younumberone@naver.com",
      address: "대구 서구 달성공원로 5 (비산동 158-22)",
      shop: "personal",
    },
    membership: {
      name: null,
      date: null,
      count: null,
      during: null,
    },
    worker: {
      bingnb: "bing03",
      star: "4.5점(9개 리뷰)",
      name: "임성규",
      mobile: "010-0891-1523",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "628733-25-211876",
      during: "11개월",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "일회성 청소",
      machine: "[스탠다드] 50kg 미만 1대",
      address: "대구 북구 내곡로 38 1층",
      date: "2025.07.12",
      time: "11:30",
      plus: null,
      memo: null,
    },
    payment: {
      service: 99000,
      extra: 0,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
    },
    sh: {
      webid: "gyqls4655",
      address: "부산광역시 수영구",
      price: 106000,
      joindate: "2025-05-30",
    },
    primemember: false,
  },
  {
    id: 4,
    number: "BING-2025-004",
    status: "done",
    date: "2025-03-28, 오후 7시 이후",
    memo: "라벨 부착해주세요.",
    price: 0,
    reservdate: "2025-05-28",
    customer: {
      name: "정유진",
      mobile: "010-3328-6834",
      email: "youjin@bingfree.co.kr",
      address: "대구 동구 안심로42길 5",
      shop: "personal",
    },
    membership: {
      name: "스탠다드",
      package: "6회권",
      date: "2025-01-25 ~",
      count: "3회 / 6회",
      during: "1개월",
    },
    worker: {
      bingnb: "bing04",
      star: "4.5점(9개 리뷰)",
      name: "김진우",
      mobile: "010-9871-4530",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강서구", "금천구"],
      },
      bank: "하나은행",
      account: "983402-24-290316",
      during: "6개월",
    },
    inquiry: {
      type: "기타 문의",
      title: "라벨 증정",
      memo: "라벨 안 주고 가셨어요 ㅠㅠ",
      file: null,
    },
    reservinfo: {
      type: "비정기 청소",
      machine: "[호시자키] 250kg 이상 1대",
      address: "대구 동구 서촌로21길 11, 2층",
      date: "2025.02.22",
      time: "12:00",
      plus: "자가점검키트",
      memo: "레포트 문자로 보내주세요",
    },
    payment: {
      service: 210000,
      extra: 4900,
      coupon: 0,
      membershipDiscount: -210000,
      extraDiscount: -4900,
    },
    sh: {
      webid: "ralwltn486",
      address: "대구광역시 수성구",
      price: 106000,
      joindate: "2025-06-05",
    },
    primemember: true,
  },
  {
    id: 5,
    number: "BING-2025-005",
    status: "waiting",
    date: "2025-01-29, 오후 9시 이후",
    memo: "세제 신청했어요 ~ ^^",
    price: 0,
    reservdate: "2025-02-21",
    customer: {
      name: "박서준",
      mobile: "010-3755-8456",
      email: "seojun@bingfree.co.kr",
      address: "대구 동구 범안로 854, 5층",
      shop: "personal",
    },
    membership: {
      name: null,
      date: null,
      count: null,
      during: null,
    },
    worker: {
      bingnb: "bing05",
      star: "4.5점(9개 리뷰)",
      name: "박찬규",
      mobile: "010-4091-1421",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "하나은행",
      account: "950402-64-127816",
      during: "7개월",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "일회성 청소",
      machine: "[프리미엄] 200Kg이상 2대",
      address: "대구 북구 복현동 산48-1",
      date: "2025.08.22",
      time: "12:30",
      plus: "자가 점검 키트",
      memo: null,
    },
    payment: {
      service: 170000,
      extra: 0,
      coupon: 0,
      mebershipDiscount: 0,
      extraDiscount: 0,
    },
    sh: {
      webid: "tngus325",
      address: "대구광역시 중구",
      price: 106000,
      joindate: "2025-06-05",
    },
    sh: {
      webid: "codus12",
      address: "대구광역시 중구",
      price: 106000,
      joindate: "2025-06-05",
    },
    primemember: false,
  },
  {
    id: 6,
    number: "BING-2025-006",
    status: "done",
    date: "2025-02-22, 오후 10시 이후",
    memo: "레포트 문자로 보내주세요",
    price: 0,
    reservdate: "2025-03-04",
    customer: {
      name: "최지은",
      mobile: "010-4635-4954",
      email: "jijibae@bingfree.co.kr",
      address: "대구 동구 초례로 6-1",
      shop: "personal",
    },
    membership: {
      name: null,
      date: null,
      count: null,
      during: null,
    },
    worker: {
      bingnb: "bing06",
      star: "4.5점(9개 리뷰)",
      name: "김재현",
      mobile: "010-0891-6521",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "대구은행",
      account: "873004-02-168816",
      during: "11개월",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "일회성 청소",
      machine: "[스탠다드] 50kg 미만 1대",
      address: "대구 서구 원대로5길 13, 1층",
      date: "2025.05.30",
      time: "12:30",
      plus: null,
      memo: null,
    },
    payment: {
      service: 99000,
      extra: 0,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
    },
    sh: {
      webid: "codus12",
      address: "대구광역시 중구",
      price: 106000,
      joindate: "2025-06-05",
    },
    primemember: false,
  },
  {
    id: 7,
    number: "BING-2025-007",
    status: "confirmed",
    date: "2025-02-12, 오후 3시 이후",
    memo: "라벨 부착해주세요.",
    price: 0,
    reservdate: "2025-01-20",
    customer: {
      name: "이동건",
      mobile: "010-6478-2314",
      email: "movegun@bingfree.co.kr",
      address: "대구 서구 내당동 31-5, 1층",
      shop: "business",
    },
    membership: {
      name: "스탠다드",
      package: "12회권",
      date: "2025-01-26 ~",
      count: "5회 / 6회",
      during: "3개월",
    },
    worker: {
      bingnb: "bing07",
      star: "4.5점(9개 리뷰)",
      name: "강성윤",
      mobile: "010-8621-4423",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강북구", "강남구"],
      },
      bank: "국민은행",
      account: "649322-41-090216",
      during: "7개월",
    },
    inquiry: {
      type: "기타 문의",
      title: "라벨 증정",
      memo: "라벨 안 주고 가셨어요 ㅠㅠ",
      file: null,
    },
    reservinfo: {
      type: "비정기 청소",
      machine: "[호시자키] 250kg 이상 1대",
      address: "대구 남구 이천로19길 38, 2층",
      date: "2025.07.12",
      time: "13:00",
      plus: "자가점검키트",
      memo: "레포트 문자로 보내주세요",
    },
    payment: {
      service: 210000,
      extra: 4900,
      coupon: 0,
      membershipDiscount: -210000,
      extraDiscount: -4900,
    },
    primemember: true,
  },
  {
    id: 8,
    number: "BING-2025-008",
    status: "waiting",
    date: "2025-01-05, 오후 1시 이후",
    memo: "세제 신청했어요 ~ ^^",
    price: 0,
    reservdate: "2025-03-21",
    customer: {
      name: "장민호",
      mobile: "010-5674-3654",
      email: "minhoho@bingfree.co.kr",
      address: "대구 달서구 서당로5길 14-3 2층",
      shop: "business",
    },
    membership: {
      name: "스탠다드",
      package: "12회권",
      date: "2025-03-13 ~",
      count: "3회 / 6회",
      during: "6개월",
    },
    worker: {
      bingnb: "bing08",
      star: "4.5점(9개 리뷰)",
      name: "장현우",
      mobile: "010-9781-4231",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "농협은행",
      account: "609872-16-382816",
      during: "8개월",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "일회성 청소",
      machine: "[스탠다드] 50kg 미만 1대",
      address: "대구 달서구 조암남로14길 3",
      date: "2025.09.22",
      time: "13:30",
      plus: "자가 점검 키트",
      memo: null,
    },
    payment: {
      service: 99000,
      extra: 4900,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
    },
    primemember: true,
  },
  {
    id: 9,
    number: "BING-2025-009",
    status: "done",
    date: "2025-02-09, 14:00",
    memo: "레포트 문자로 보내주세요",
    price: 0,
    reservdate: "2025-02-19",
    customer: {
      name: "하윤아",
      mobile: "010-7542-3922",
      email: "hahayoun@bingfree.co.kr",
      address: "대구 서구 서대구로 21-1",
      shop: "personal",
    },
    membership: {
      name: null,
      date: null,
      count: null,
      during: null,
    },
    worker: {
      bingnb: "bing09",
      star: "4.5점(9개 리뷰)",
      name: "신정빈",
      mobile: "010-2541-0425",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "하나은행",
      account: "698342-34-211866",
      during: "4개월",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "일회성 청소",
      machine: "[스탠다드] 50kg 미만 1대",
      address: "대구 서구 당산로23동길 3",
      date: "2025.03.22",
      time: "14:00",
      plus: null,
      memo: null,
    },
    payment: {
      service: 99000,
      extra: 0,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
    },
    primemember: false,
  },
  {
    id: 10,
    number: "BING-2025-010",
    status: "confirmed",
    date: "2025-03-26, 오후 3시 이후",
    memo: "라벨 부착해주세요.",
    price: 0,
    reservdate: "2025-02-11",
    customer: {
      name: "문채원",
      mobile: "010-5378-6344",
      email: "doorone@bingfree.co.kr",
      address: "대구 동구 이노밸리로 322, 비전스퀘어 2",
      shop: "business",
    },
    membership: {
      name: "스탠다드",
      package: "6회권",
      date: "2025-01-22 ~",
      count: "6회 / 6회",
      during: "3개월",
    },
    worker: {
      bingnb: "bing10",
      star: "4.5점(9개 리뷰)",
      name: "이승규",
      mobile: "010-9451-2641",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "하나은행",
      account: "678342-98-258196",
      during: "5개월",
    },
    inquiry: {
      type: "기타 문의",
      title: "라벨 증정",
      memo: "라벨 안 주고 가셨어요 ㅠㅠ",
      file: null,
    },
    reservinfo: {
      type: "비정기 청소",
      machine: "[호시자키] 250kg 이상 1대",
      address: "대구 수성구 화랑로7길 23-5",
      date: "2025.05.24",
      time: "14:00",
      plus: "자가점검키트",
      memo: "레포트 문자로 보내주세요",
    },
    payment: {
      service: 210000,
      extra: 4900,
      coupon: 0,
      membershipDiscount: -210000,
      extraDiscount: -4900,
    },
    primemember: true,
  },
  {
    id: 11,
    number: "BING-2025-011",
    status: "waiting",
    date: "2025-01-27, 오후 5시 이후",
    memo: "세제 신청했어요 ~ ^^",
    price: 0,
    reservdate: "2025-08-13",
    customer: {
      name: "윤도현",
      mobile: "010-6343-1486",
      email: "yoondh@bingfree.co.kr",
      address: "대구 남구 이천로7길 3, 1층",
      shop: "business",
    },
    membership: {
      name: "스탠다드",
      package: "6회권",
      date: "2025-02-04 ~",
      count: "3회 / 6회",
      during: "1개월",
    },
    worker: {
      bingnb: "bing11",
      star: "4.5점(9개 리뷰)",
      name: "김명우",
      mobile: "010-6566-4431",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "483002-94-873815",
      during: "11개월",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "일회성 청소",
      machine: "[디럭스] 100~200kg 1대",
      address: "대구 동구 서촌로 89",
      date: "2025.11.22",
      time: "14:00",
      plus: "자가 점검 키트",
      memo: null,
    },
    payment: {
      service: 150000,
      extra: 0,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
    },
    primemember: true,
  },
  {
    id: 12,
    number: "BING-2025-012",
    status: "assigned",
    date: "2025-01-20, 오후 8시 이후",
    memo: "레포트 문자로 보내주세요",
    price: 0,
    reservdate: "2025-08-27",
    customer: {
      name: "백예린",
      mobile: "010-7848-3409",
      email: "yerin@bingfree.co.kr",
      address: "대구 남구 안지랑로 21 (대명동 217-6)",
      shop: "personal",
    },
    membership: {
      name: null,
      date: null,
      count: null,
      during: null,
    },
    worker: {
      bingnb: "bing12",
      star: "4.5점(9개 리뷰)",
      name: "박재훈",
      mobile: "010-7561-5331",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "789302-54-734416",
      during: "10개월",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "일회성 청소",
      machine: "[스탠다드] 50kg 미만 1대",
      address: "대구 북구 학정동 926-1 1층",
      date: "2025.12.21",
      time: "14:30",
      plus: null,
      memo: null,
    },
    payment: {
      service: 99000,
      extra: 0,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
    },
    primemember: false,
  },
  {
    id: 13,
    number: "BING-2025-013",
    status: "confirmed",
    date: "2025-01-09, 오후 10시 이후",
    memo: "라벨 부착해주세요.",
    price: 0,
    reservdate: "2025-06-01",
    customer: {
      name: "서지호",
      mobile: "010-8677-3174",
      email: "jihoya@bingfree.co.kr",
      address: "대구 동구 서촌로21길 11",
      shop: "business",
    },
    membership: {
      name: "스탠다드",
      package: "12회권",
      date: "2025-03-09 ~",
      count: "1회 / 6회",
      during: "3개월",
    },
    worker: {
      bingnb: "bing13",
      star: "4.5점(9개 리뷰)",
      name: "이태곤",
      mobile: "010-4641-1533",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "대구은행",
      account: "982002-06-352616",
      during: "2개월",
    },
    inquiry: {
      type: "기타 문의",
      title: "라벨 증정",
      memo: "라벨 안 주고 가셨어요 ㅠㅠ",
      file: null,
    },
    reservinfo: {
      type: "비정기 청소",
      machine: "[호시자키] 250kg 이상 1대",
      address: "대구 수성구 수성못길 14",
      date: "2025.08.22",
      time: "14:00",
      plus: "자가점검키트",
      memo: "레포트 문자로 보내주세요",
    },
    payment: {
      service: 210000,
      extra: 4900,
      coupon: 0,
      membershipDiscount: -210000,
      extraDiscount: -4900,
    },
    primemember: true,
  },
  {
    id: 14,
    number: "BING-2025-014",
    status: "waiting",
    date: "2025-01-18, 14:00",
    memo: "세제 신청했어요 ~ ^^",
    price: 0,
    reservdate: "2025-03-06",
    customer: {
      name: "김지수",
      mobile: "010-7456-3078",
      email: "jisuu@bingfree.co.kr",
      address: "대구 달서구 조암남로20길 41",
      shop: "personal",
    },
    membership: {
      name: null,
      date: null,
      count: null,
      during: null,
    },
    worker: {
      bingnb: "bing14",
      star: "4.5점(9개 리뷰)",
      name: "김재호",
      mobile: "010-0878-4621",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "876752-34-842856",
      during: "4개월",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "일회성 청소",
      machine: "[스탠다드] 50kg 미만 1대",
      address: "대구 북구 호국로 300-22",
      date: "2025.05.30",
      time: "14:00",
      plus: "자가 점검 키트",
      memo: null,
    },
    payment: {
      service: 99000,
      extra: 4900,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
    },
    primemember: false,
  },
  {
    id: 15,
    number: "BING-2025-015",
    status: "assigned",
    date: "2025-02-15, 오후 3시 이후",
    memo: "레포트 문자로 보내주세요",
    price: 0,
    reservdate: "2025-02-26",
    customer: {
      name: "강다현",
      mobile: "010-8699-1534",
      email: "dahyunn@bingfree.co.kr",
      address: "대구 수성구 들안로 176-1",
      shop: "business",
    },
    membership: {
      name: "스탠다드",
      package: "6회권",
      date: "2025-01-04 ~",
      count: "5회 / 6회",
      during: "2개월",
    },
    worker: {
      bingnb: "bing15",
      star: "4.5점(9개 리뷰)",
      name: "최현우",
      mobile: "010-7691-5347",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "대구은행",
      account: "609432-36-254840",
      during: "7개월",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "일회성 청소",
      machine: "[스탠다드] 50kg 미만 1대",
      address: "대구 수성구 들안로4길 35",
      date: "2025-08-22",
      time: "14:00",
      plus: null,
      memo: null,
    },
    payment: {
      service: 99000,
      extra: 0,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
    },
    primemember: true,
  },
  {
    id: 16,
    number: "BING-2025-016",
    status: "done", // (예시: 랜덤)
    date: "2025-02-15, 오후 3시 이후",
    memo: "레포트 받을래요~",
    price: 0,
    reservdate: "2025-02-20",
    customer: {
      name: "박소연",
      mobile: "010-7182-3345",
      email: "soyeon.park@bingfree.co.kr",
      address: "대구 수성구 국채보상로186길 81, 2층",
      shop: "business",
    },
    membership: {
      name: "스탠다드",
      package: "6회권",
      date: "2025-01-04 ~",
      count: "5회 / 6회",
      during: "2개월",
    },
    worker: {
      bingnb: "bing16",
      number: "bing01",
      star: "4.5점(9개 리뷰)",
      name: "이정후",
      mobile: "010-3291-4613",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "농협은행",
      account: "609432-54-241857",
      during: "11개월",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "일회성 청소",
      machine: "[스탠다드] 50kg 미만 1대",
      address: "대구 남구 봉덕로 26, 1층",
      date: "2025-09-22",
      time: "18:00",
      plus: null,
      memo: null,
    },
    payment: {
      service: 99000,
      extra: 0,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
    },
    primemember: false, // (예시: 랜덤)
  },

  // id: 17
  {
    id: 17,
    number: "BING-2025-017",
    status: "waiting", // (예시: 랜덤)
    date: "2025-02-15, 오후 3시 이후",
    memo: "레포트 받을래요~",
    price: 0,
    reservdate: "2025-02-20",
    customer: {
      name: "이정훈",
      mobile: "010-5923-1108",
      email: "junghoon.lee@bingfree.co.kr",
      address: "대구 남구 현충로 54",
      shop: "business",
    },
    membership: {
      name: "스탠다드",
      package: "6회권",
      date: "2025-01-04 ~",
      count: "5회 / 6회",
      during: "2개월",
    },
    worker: {
      bingnb: "bing17",
      star: "4.5점(9개 리뷰)",
      name: "김혜성",
      mobile: "010-4237-2081",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "733003-02-442576",
      during: "9개월",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "일회성 청소",
      machine: "[스탠다드] 50kg 미만 1대",
      address: "대구 수성구 국채보상로43길 56, 2층",
      date: "2025-08-22",
      time: "14:00",
      plus: null,
      memo: null,
    },
    payment: {
      service: 99000,
      extra: 0,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
    },
    primemember: true, // (예시: 랜덤)
  },

  // id: 18
  {
    id: 18,
    number: "BING-2025-018",
    status: "confirmed", // (예시: 랜덤)
    date: "2025-02-15, 오후 3시 이후",
    memo: "레포트 받을래요~",
    price: 0,
    reservdate: "2025-02-20",
    customer: {
      name: "최민지",
      mobile: "010-8856-4401",
      email: "minji.choi@bingfree.co.kr",
      address: "대구 동구 신서로 20 1층",
      shop: "business",
    },
    membership: {
      name: "스탠다드",
      package: "6회권",
      date: "2025-01-04 ~",
      count: "5회 / 6회",
      during: "2개월",
    },
    worker: {
      bingnb: "bing18",
      star: "4.5점(9개 리뷰)",
      name: "문동주",
      mobile: "010-7457-3521",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "대구은행",
      account: "460032-94-290312",
      during: "5개월",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "일회성 청소",
      machine: "[스탠다드] 50kg 미만 1대",
      address: "대구 서구 내당동 134-5, 1층",
      date: "2025-08-22",
      time: "14:00",
      plus: null,
      memo: null,
    },
    payment: {
      service: 99000,
      extra: 0,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
    },
    primemember: false, // (예시: 랜덤)
  },

  // id: 19
  {
    id: 19,
    number: "BING-2025-019",
    status: "assigned", // (예시: 랜덤)
    date: "2025-02-15, 오후 3시 이후",
    memo: "레포트 받을래요~",
    price: 0,
    reservdate: "2025-02-20",
    customer: {
      name: "한지훈",
      mobile: "010-2323-9902",
      email: "jihoon.han@bingfree.co.kr",
      address: "대구 서구 당산로41동길 37 (내당동 427-16)",
      shop: "business",
    },
    membership: {
      name: "스탠다드",
      package: "6회권",
      date: "2025-01-04 ~",
      count: "5회 / 6회",
      during: "2개월",
    },
    worker: {
      bingnb: "bing19",
      star: "4.5점(9개 리뷰)",
      name: "임동원",
      mobile: "010-5381-0861",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "일회성 청소",
      machine: "[스탠다드] 50kg 미만 1대",
      address: "대구 서구 달성공원로 5 (비산동 158-22)",
      date: "2025-08-22",
      time: "14:00",
      plus: null,
      memo: null,
    },
    payment: {
      service: 99000,
      extra: 0,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
    },
    primemember: true, // (예시: 랜덤)
  },

  // id: 20
  {
    id: 20,
    number: "BING-2025-020",
    status: "waiting", // (예시: 랜덤)
    date: "2025-02-15, 오후 3시 이후",
    memo: "레포트 받을래요~",
    price: 0,
    reservdate: "2025-02-20",
    customer: {
      name: "윤세영",
      mobile: "010-6667-2223",
      email: "seyoung.yoon@bingfree.co.kr",
      address: "대구 달서구 조암남로5길 23-2",
      shop: "business",
    },
    membership: {
      name: "스탠다드",
      package: "6회권",
      date: "2025-01-04 ~",
      count: "5회 / 6회",
      during: "2개월",
    },
    worker: {
      bingnb: "bing20",
      star: "4.5점(9개 리뷰)",
      name: "강수호",
      mobile: "010-3687-2591",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "하나은행",
      account: "250402-65-483811",
      during: "11개월",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "일회성 청소",
      machine: "[스탠다드] 50kg 미만 1대",
      address: "대구 달서구 상화로5길 22 1층",
      date: "2025-08-22",
      time: "14:30",
      plus: null,
      memo: null,
    },
    payment: {
      service: 99000,
      extra: 0,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
    },
    primemember: false, // (예시: 랜덤)
  },
  // id: 21
  {
    id: 21,
    number: "BING-2025-021",
    status: "waiting", // (예시: 랜덤)
    date: "2025-02-20, 오후 5시 이후",
    memo: "세제주세요",
    price: 0,
    reservdate: "2025-02-20",
    customer: {
      name: "박나린",
      mobile: "010-4933-2413",
      email: "narinepark@bingfree.co.kr",
      address: "대구 서구 달구벌대로375길 23-1 1층",
      shop: "business",
    },
    membership: {
      name: "스탠다드",
      package: "6회권",
      date: "2025-01-04 ~",
      count: "3회 / 6회",
      during: "1개월",
    },
    worker: {
      bingnb: "bing21",
      star: "4.5점(9개 리뷰)",
      name: "이용국",
      mobile: "010-4211-6881",
      email: "yongkuk@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "하나은행",
      account: "621402-36-285096",
      during: "4개월",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "일회성 청소",
      machine: "[스탠다드] 50kg 미만 1대",
      address: "대구 서구 달구벌대로375길 23-1 1층",
      date: "2025-08-22",
      time: "17:00",
      plus: null,
      memo: null,
    },
    payment: {
      service: 99000,
      extra: 0,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
    },
    primemember: false, // (예시: 랜덤)
  },
]);
// 지역 선택 데이터
export const koreaLocations = reactive({
  서울특별시: [
    "강남구",
    "강동구",
    "강북구",
    "강서구",
    "관악구",
    "광진구",
    "구로구",
    "금천구",
    "노원구",
    "도봉구",
    "동대문구",
    "동작구",
    "마포구",
    "서대문구",
    "서초구",
    "성동구",
    "성북구",
    "송파구",
    "양천구",
    "영등포구",
    "용산구",
    "은평구",
    "종로구",
    "중구",
    "중랑구",
  ],
  부산광역시: [
    "강서구",
    "금정구",
    "기장군",
    "남구",
    "동구",
    "동래구",
    "부산진구",
    "북구",
    "사상구",
    "사하구",
    "서구",
    "수영구",
    "연제구",
    "영도구",
    "중구",
    "해운대구",
  ],
  대구광역시: [
    "남구",
    "달서구",
    "달성군",
    "동구",
    "북구",
    "서구",
    "수성구",
    "중구",
  ],
  인천광역시: [
    "강화군",
    "계양구",
    "남동구",
    "동구",
    "미추홀구",
    "부평구",
    "서구",
    "연수구",
    "옹진군",
    "중구",
  ],
  광주광역시: ["광산구", "남구", "동구", "북구", "서구"],
  대전광역시: ["대덕구", "동구", "서구", "유성구", "중구"],
  울산광역시: ["남구", "동구", "북구", "울주군", "중구"],
  세종특별자치시: ["세종시"],
  경기도: [
    "가평군",
    "고양시",
    "과천시",
    "광명시",
    "광주시",
    "구리시",
    "군포시",
    "김포시",
    "남양주시",
    "동두천시",
    "부천시",
    "성남시",
    "수원시",
    "시흥시",
    "안산시",
    "안성시",
    "안양시",
    "양주시",
    "양평군",
    "여주시",
    "연천군",
    "오산시",
    "용인시",
    "의왕시",
    "의정부시",
    "이천시",
    "파주시",
    "평택시",
    "포천시",
    "하남시",
    "화성시",
  ],
  강원도: [
    "강릉시",
    "고성군",
    "동해시",
    "삼척시",
    "속초시",
    "양구군",
    "양양군",
    "영월군",
    "원주시",
    "인제군",
    "정선군",
    "철원군",
    "춘천시",
    "태백시",
    "평창군",
    "홍천군",
    "화천군",
    "횡성군",
  ],
  충청북도: [
    "괴산군",
    "단양군",
    "보은군",
    "영동군",
    "옥천군",
    "음성군",
    "제천시",
    "증평군",
    "진천군",
    "청주시",
    "충주시",
  ],
  충청남도: [
    "계룡시",
    "공주시",
    "금산군",
    "논산시",
    "당진시",
    "보령시",
    "부여군",
    "서산시",
    "서천군",
    "아산시",
    "예산군",
    "천안시",
    "청양군",
    "태안군",
    "홍성군",
  ],
  전라북도: [
    "고창군",
    "군산시",
    "김제시",
    "남원시",
    "무주군",
    "부안군",
    "순창군",
    "완주군",
    "익산시",
    "임실군",
    "장수군",
    "전주시",
    "정읍시",
    "진안군",
  ],
  전라남도: [
    "강진군",
    "고흥군",
    "곡성군",
    "광양시",
    "구례군",
    "나주시",
    "담양군",
    "목포시",
    "무안군",
    "보성군",
    "순천시",
    "신안군",
    "여수시",
    "영광군",
    "영암군",
    "완도군",
    "장성군",
    "장흥군",
    "진도군",
    "함평군",
    "해남군",
    "화순군",
  ],
  경상북도: [
    "경산시",
    "경주시",
    "고령군",
    "구미시",
    "군위군",
    "김천시",
    "문경시",
    "봉화군",
    "상주시",
    "성주군",
    "안동시",
    "영덕군",
    "영양군",
    "영주시",
    "영천시",
    "예천군",
    "울릉군",
    "울진군",
    "의성군",
    "청도군",
    "청송군",
    "칠곡군",
    "포항시",
  ],
  경상남도: [
    "거제시",
    "거창군",
    "고성군",
    "김해시",
    "남해군",
    "밀양시",
    "사천시",
    "산청군",
    "양산시",
    "의령군",
    "진주시",
    "창녕군",
    "창원시",
    "통영시",
    "하동군",
    "함안군",
    "함양군",
    "합천군",
  ],
  제주특별자치도: ["서귀포시", "제주시"],
});
// 테이블 헤더 데이터
export const TableHeaders = [
  { key: "item", label: "결제 내역" },
  { key: "amount", label: "결제금액" },
  { key: "date", label: "결제일" },
  { key: "period", label: "이용 기간" },
  { key: "status", label: "상태" },
  { key: "receipt", label: "영수증" },
];

// 테이블 내용 데이터
export const TableData = [
  {
    item: "호시자키(250kg~) 6회권",
    amount: "1,134,000원",
    date: "2025.03.17 14:00",
    period: "2025.03.17 ~ 2026.03.17",
    status: "결제 완료",
    receipt: "영수증 보기",
    receiptUrl: "#",
  },
];
// 클레임 내용 데이터

export const fullclaimList = reactive([
  {
    id: 1,
    number: "1",
    status: "confirmed",
    date: "2025-03-18",
    claimdate: "2025.03.21",
    memo: "라벨 부착해주세요.",
    price: 0,
    store: "사업자 ",
    customer: {
      name: "고윤정",
      claimId: "CLM250501",
      detailclaim: "서비스 품질",
      email: "yunjung@naver.com",
      mobile: "010-1451-1234",
      csSencitive: "신규/초회",
      avatar: "/prime/cs_first.png",
      address: "대구 서구 원대로13길 1, 1층 (원대동1가 1-1)",
    },
    membership: {
      name: "호시자키",
      package: "6회권",
      date: "2025-03-17 ~",
      count: "2회 / 6회",
      during: "3개월",
    },
    worker: {
      star: "4.5점(9개 리뷰)",
      name: "차승준",
      mobile: "010-4181-4358",
      email: "mrkim@bingfree.co.kr",
      gender: "female",
      health: false,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: "기타 문의",
      title: "라벨 증정",
      memo: "라벨 안 주고 가셨어요 ㅠㅠ",
      file: null,
    },
    reservinfo: {
      type: "서비스 품질",
      machine: "신규/초회",
      address: "c/s이력 없음",

      date: "2025.03.21",
      plus: "자가점검키트",
      memo: "청소 후 냄새 남음. 고객 불만 높음. 5/16 재방문 요청됨.",
    },
    payment: {
      service: 210000,
      extra: 4900,
      coupon: 0,
      membershipDiscount: -210000,
      extraDiscount: -4900,
    },
    sh: {
      webid: "qortjf325",
      address: "대구광역시 동구",
      price: 96000,
      joindate: "2025-06-05",
    },
    primemember: true,
  },
  {
    id: 2,
    number: "2",
    status: "waiting",
    date: "2025-06-18",
    claimdate: "2025.06.21",
    memo: "세제 신청했어요 ~ ^^",
    price: 0,
    store: "사업자",
    customer: {
      name: "유세은",
      claimId: "CLM250401",
      detailclaim: "시간 관련",
      email: "youseeun@naver.com",
      mobile: "010-1431-4141",
      csSencitive: "주의고객",
      avatar: "/prime/cs_second.png",
      address: "대구 수성구 고모로 188",
      shop: "personal",
      date: "2025-02-04",
    },
    membership: {
      name: null,
      date: null,
      count: null,
      during: null,
    },
    worker: {
      star: "4.5점(9개 리뷰)",
      name: "최일용",
      mobile: "010-1121-8571",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "시간 관련",
      machine: "주의고객",
      address: "c/s이력 없음",

      date: "2025.06.21",
      plus: "자가점검키트",
      memo: "예약 시간보다 30분 늦게 도착. 고객 대기 불만 표출됨. 다음 방문 시 시간 엄수 필요.",
    },
    payment: {
      service: 99000,
      extra: 4900,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
    },
    primemember: false,
  },
  {
    id: 3,
    number: "3",
    status: "assigned",
    date: "2025-05-15",
    claimdate: "2025.05.21",
    memo: "레포트 문자로 보내주세요",
    price: 0,
    store: "사업자",
    customer: {
      name: "이지유",
      claimId: "CLM250515",
      detailclaim: "서비스 품질",
      mobile: "010-2747-4634",
      csSencitive: "민감고객",
      avatar: "/prime/cs_third.png",
      email: "jiyou@naver.com",
      address: "대구 수성구 고모로 15-1",
      shop: "personal",
    },
    membership: {
      name: null,
      date: null,
      count: null,
      during: null,
    },
    worker: {
      star: "4.5점(9개 리뷰)",
      name: "김일훈",
      mobile: "010-2751-8851",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "서비스 품질",
      machine: "민감고객",
      address: "c/s이력 있음",

      date: "2025.04.21",
      plus: "자가점검키트",
      memo: "청소 후 얼음 색상과 맛 변화 없음. 효과에 대한 의구심 제기됨.",
    },
    payment: {
      service: 99000,
      extra: 0,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
    },
    primemember: false,
  },
  {
    id: 4,
    number: "4",
    status: "done",
    date: "2025-03-28",
    claimdate: "2025.03.28",
    memo: "라벨 부착해주세요.",
    price: 0,
    reservdate: "2025-05-28",
    store: "사업자 ",
    customer: {
      name: "정유진",
      claimId: "CLM250328",
      detailclaim: "응대/매너",
      mobile: "010-7265-8677",
      csSencitive: "고위험고객",
      avatar: "/prime/cs_fourd.png",
      email: "youjine@bingfree.co.kr",
      address: " 대구 수성구 수성못길 20 1층",
      shop: "personal",
    },
    membership: {
      name: "스탠다드",
      package: "6회권",
      date: "2025-01-25 ~",
      count: "3회 / 6회",
      during: "1개월",
    },
    worker: {
      star: "4.5점(9개 리뷰)",
      name: "박태훈",
      mobile: "010-4745-1041",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: "기타 문의",
      title: "라벨 증정",
      memo: "라벨 안 주고 가셨어요 ㅠㅠ",
      file: null,
    },
    reservinfo: {
      type: "응대/매너",
      machine: "고위험고객",
      address: "c/s이력 있음",

      date: "2025-04-18 , 2025-05-28 ",
      plus: "자가점검키트",
      memo: "방문 기사 응대 태도 관련 불만 제기. 말투와 설명 부족함 언급됨. 교육 필요 요청.",
    },
    payment: {
      service: 210000,
      extra: 4900,
      coupon: 0,
      membershipDiscount: -210000,
      extraDiscount: -4900,
    },
    primemember: true,
  },
  {
    id: 5,
    number: "5",
    status: "waiting",
    date: "2025-01-29",
    claimdate: "2025.01.21",
    memo: "세제 신청했어요 ~ ^^",
    price: 0,
    store: "개인",
    reservdate: "2025-02-21",
    customer: {
      name: "박서준",
      claimId: "CLM250129",
      detailclaim: "요금/결제",
      mobile: "010-0876-2534",
      csSencitive: "신규/초회",
      avatar: "/prime/cs_first.png",
      email: "seojun@bingfree.co.kr",
      address: "대구 수성구 들안로8길 29",
      shop: "personal",
    },
    membership: {
      name: null,
      date: null,
      count: null,
      during: null,
    },
    worker: {
      star: "4.5점(9개 리뷰)",
      name: "임지용",
      mobile: "010-2771-1631",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "요금/결제",
      machine: "신규/초회",
      address: "c/s이력 없음",

      date: "",
      plus: "자가점검키트",
      memo: "청소 구독 혜택이 제대로 적용되지 않음. 차액 환불 요청 있음.",
    },
    payment: {
      service: 99000,
      extra: 4900,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
    },
    primemember: false,
  },
  {
    id: 6,
    number: "6",
    status: "done",
    date: "2025-02-22",
    claimdate: "2025.02.24",
    memo: "레포트 문자로 보내주세요",
    price: 0,
    store: "개인 ",
    customer: {
      name: "최지은",
      claimId: "CLM250222",
      detailclaim: "예약/시스템",
      mobile: "010-7896-0788",
      email: "jieuny@bingfree.co.kr",
      csSencitive: "신규/초회",
      avatar: "/prime/cs_first.png",
      address: "대구 수성구 알파시티1로40길 6, 더아르코호텔 2층",
      shop: "personal",
    },
    membership: {
      name: null,
      date: null,
      count: null,
      during: null,
    },
    worker: {
      star: "4.5점(9개 리뷰)",
      name: "이무림",
      mobile: "010-1831-7794",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "예약/시스템",
      machine: "신규/초회",
      address: "c/s이력 없음",

      date: "",
      plus: "자가점검키트",
      memo: "예약 변경이 반영되지 않아 기사 잘못 방문. 고객 불쾌감 표시.",
    },
    payment: {
      service: 99000,
      extra: 0,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
    },
    primemember: false,
  },
  {
    id: 7,
    number: "7",
    status: "confirmed",
    date: "2025-02-12",
    claimdate: "2025.02.21",
    memo: "라벨 부착해주세요.",
    price: 0,
    store: "사업자",
    customer: {
      name: "이동건",
      claimId: "CLM250212",
      detailclaim: "기타",
      mobile: "010-4850-1694",
      email: "movegun@bingfree.co.kr",
      csSencitive: "신규/초회",
      avatar: "/prime/cs_first.png",
      address: "대구 수성구 동대구로14길 15-6, 2층",
      shop: "business",
    },
    membership: {
      name: "스탠다드",
      package: "12회권",
      date: "2025-01-26 ~",
      count: "5회 / 6회",
      during: "3개월",
    },
    worker: {
      star: "4.5점(9개 리뷰)",
      name: "박진만",
      mobile: "010-1831-4890",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: "기타 문의",
      title: "라벨 증정",
      memo: "라벨 안 주고 가셨어요 ㅠㅠ",
      file: null,
    },
    reservinfo: {
      type: "기타",
      machine: "신규/초회",
      address: "c/s이력 없음",

      date: "",
      plus: "자가점검키트",
      memo: "매장 내 전기 미사용 가능 시간으로 청소 중단됨. 운영팀과 조율 요청됨.",
    },
    payment: {
      service: 210000,
      extra: 4900,
      coupon: 0,
      membershipDiscount: -210000,
      extraDiscount: -4900,
    },
    primemember: true,
  },
  {
    id: 8,
    number: "8",
    status: "waiting",
    date: "2025-01-05",
    claimdate: "2025.01.07",
    memo: "세제 신청했어요 ~ ^^",
    price: 0,
    store: "개인",
    customer: {
      name: "장민호",
      claimId: "CLM250105",
      detailclaim: "시간 관련",
      mobile: "010-5318-6734",
      csSencitive: "민감고객",
      avatar: "/prime/cs_second.png",
      email: "minhou@bingfree.co.kr",
      address: "대구 수성구 용학로 361",
      shop: "business",
    },
    membership: {
      name: "스탠다드",
      package: "12회권",
      date: "2025-03-13 ~",
      count: "3회 / 6회",
      during: "6개월",
    },
    worker: {
      star: "4.5점(9개 리뷰)",
      name: "이승후",
      mobile: "010-1841-9021",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "시간 관련",
      machine: "민감고객",
      address: "c/s이력 있음",

      date: "2025.01.07",
      plus: "자가점검키트",
      memo: "일정 사전 고지 없이 시간 변경되어 고객 혼선 발생. 불만 접수됨.",
    },
    payment: {
      service: 99000,
      extra: 4900,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
    },
    primemember: true,
  },
  {
    id: 9,
    number: "9",
    status: "done",
    date: "2025-02-09",
    claimdate: "2025.02.21",
    memo: "레포트 문자로 보내주세요",
    price: 0,
    reservdate: "2025-02-19",
    store: "개인 ",
    customer: {
      name: "하윤아",
      claimId: "CLM250221",
      detailclaim: "기타",
      mobile: "010-3547-9970",
      csSencitive: "민감고객",
      avatar: "/prime/cs_third.png",
      email: "hayouna@bingfree.co.kr",
      address: "대구 동구 팔공로70길 2, 1층",
      shop: "personal",
    },
    membership: {
      name: null,
      date: null,
      count: null,
      during: null,
    },
    worker: {
      star: "4.5점(9개 리뷰)",
      name: "심태희",
      mobile: "010-2621-8804",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "기타",
      machine: "민감고객",
      address: "c/s이력 있음",

      date: "2025-02-19",
      plus: "자가점검키트",
      memo: "현장 접근 어려움(지하 창고)으로 장비 운반 지연 발생. 사전 안내 필요.",
    },
    payment: {
      service: 99000,
      extra: 0,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
    },
    primemember: false,
  },
  {
    id: 10,
    number: "10",
    status: "confirmed",
    date: "2025-03-26",
    claimdate: "2025.03.27",
    memo: "라벨 부착해주세요.",
    price: 0,
    store: "사업자 ",
    customer: {
      name: "문채원",
      claimId: "CLM250326",
      detailclaim: "응대/매너",
      mobile: "010-1310-3124",
      csSencitive: "신규/초회",
      avatar: "/prime/cs_first.png",
      email: "mooncha@bingfree.co.kr",
      address: "대구 달서구 상화로7길 38 1층",
      shop: "business",
    },
    membership: {
      name: "스탠다드",
      package: "6회권",
      date: "2025-01-22 ~",
      count: "6회 / 6회",
      during: "3개월",
    },
    worker: {
      star: "4.5점(9개 리뷰)",
      name: "이우빈",
      mobile: "010-1255-7921",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: "기타 문의",
      title: "라벨 증정",
      memo: "라벨 안 주고 가셨어요 ㅠㅠ",
      file: null,
    },
    reservinfo: {
      type: "응대/매너",
      machine: "신규/초회",
      address: "c/s이력 없음",

      date: "",
      plus: "자가점검키트",
      memo: "고객 질문에 무성의한 대응으로 신뢰도 하락. 정중한 응대 요청됨.",
    },
    payment: {
      service: 210000,
      extra: 4900,
      coupon: 0,
      membershipDiscount: -210000,
      extraDiscount: -4900,
    },
    primemember: true,
  },
  {
    id: 11,
    number: "11",
    status: "waiting",
    date: "2025-01-27",
    claimdate: "2025.01.29",
    memo: "세제 신청했어요 ~ ^^",
    price: 0,
    store: "사업자 ",
    customer: {
      name: "윤도현",
      claimId: "CLM250127",
      detailclaim: "시간 관련",
      mobile: "010-2015-0923",
      csSencitive: "민감고객",
      avatar: "/prime/cs_second.png",
      email: "yoondo@bingfree.co.kr",
      address: "대구 달서구 진천로 38",
      shop: "business",
    },
    membership: {
      name: "스탠다드",
      package: "6회권",
      date: "2025-02-04 ~",
      count: "3회 / 6회",
      during: "1개월",
    },
    worker: {
      star: "4.5점(9개 리뷰)",
      name: "강현규",
      mobile: "010-0751-7421",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "시간 관련",
      machine: "민감고객",
      address: "c/s이력 있음",

      date: "2025.01.29",
      plus: "자가점검키트",
      memo: "기사 도착 전 연락 없었음. 고객 당황하며 재방문 요구함.",
    },
    payment: {
      service: 99000,
      extra: 4900,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
    },
    primemember: true,
  },
  {
    id: 12,
    number: "12",
    status: "assigned",
    date: "2025-01-20",
    claimdate: "2025.01.21",
    memo: "레포트 문자로 보내주세요",
    price: 0,
    reservdate: "2025-08-27",
    store: "개인 ",
    customer: {
      name: "백예린",
      claimId: "CLM250120",
      detailclaim: "요금/결제",
      mobile: "010-1025-9882",
      email: "yerinn@bingfree.co.kr",
      csSencitive: "신규/초회",
      avatar: "/prime/cs_first.png",
      address: "대구 달서구 상화로 157-1",
      shop: "personal",
    },
    membership: {
      name: null,
      date: null,
      count: null,
      during: null,
    },
    worker: {
      star: "4.5점(9개 리뷰)",
      name: "김민규",
      mobile: "010-4521-4101",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "요금/결제",
      machine: "신규/초회",
      address: "c/s이력 없음",

      date: "",
      plus: "자가점검키트",
      memo: "추가 비용 발생 안내 미흡으로 고객 오해 발생. 정확한 요금 안내 요청함.",
    },
    payment: {
      service: 99000,
      extra: 0,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
    },
    primemember: false,
  },
  {
    id: 13,
    number: "13",
    status: "confirmed",
    date: "2025-01-09",
    claimdate: "2025.01.11",
    memo: "라벨 부착해주세요.",
    price: 0,
    store: "사업자 ",
    customer: {
      name: "서지호",
      claimId: "CLM250109",
      detailclaim: "서비스 품질",
      mobile: "010-1942-1943",
      email: "jihou@bingfree.co.kr",
      csSencitive: "주의고객",
      avatar: "/prime/cs_third.png",
      address: "대구 서구 서대구로 3",
      shop: "business",
    },
    membership: {
      name: "스탠다드",
      package: "12회권",
      date: "2025-03-09 ~",
      count: "1회 / 6회",
      during: "3개월",
    },
    worker: {
      star: "4.5점(9개 리뷰)",
      name: "신현빈",
      mobile: "010-6741-0231",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: "기타 문의",
      title: "라벨 증정",
      memo: "라벨 안 주고 가셨어요 ㅠㅠ",
      file: null,
    },
    reservinfo: {
      type: "서비스 품질",
      machine: "주의고객",
      address: "c/s이력 있음",

      date: "2025.01.11",
      plus: "자가점검키트",
      memo: "얼음 저장고 내부 세척 누락 발견. 현장 확인 요청됨.",
    },
    payment: {
      service: 210000,
      extra: 4900,
      coupon: 0,
      membershipDiscount: -210000,
      extraDiscount: -4900,
    },
    primemember: true,
  },
  {
    id: 14,
    number: "14",
    status: "waiting",
    date: "2025-01-18",
    claimdate: "2025.01.21",
    memo: "세제 신청했어요 ~ ^^",
    price: 0,
    store: "개인 ",
    customer: {
      name: "김지수",
      claimId: "CLM250118",
      detailclaim: "시간 관련",
      mobile: "010-3982-1872",
      csSencitive: "신규/초회",
      avatar: "/prime/cs_first.png",
      email: "jisuu@bingfree.co.kr",
      address: "대구 수성구 용학로 361, 1층",
      shop: "personal",
    },
    membership: {
      name: null,
      date: null,
      count: null,
      during: null,
    },
    worker: {
      star: "4.5점(9개 리뷰)",
      name: "강승빈",
      mobile: "010-6431-1427",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "시간 관련",
      machine: "신규/초회",
      address: "c/s이력 없음",

      date: "",
      plus: "자가점검키트",
      memo: "일정 사전 고지 없이 시간 변경되어 고객 혼선 발생. 불만 접수됨.",
    },
    payment: {
      service: 99000,
      extra: 4900,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
    },
    primemember: false,
  },
  {
    id: 15,
    number: "15",
    status: "assigned",
    date: "2025-02-15",
    claimdate: "2025.02.21",
    memo: "레포트 문자로 보내주세요",
    price: 0,
    store: "사업자 ",
    customer: {
      name: "강다현",
      mobile: "010-9225-8742",
      claimId: "CLM250221",
      detailclaim: "서비스 품질",
      email: "dahyun@bingfree.co.kr",
      csSencitive: "민감고객",
      avatar: "/prime/cs_second.png",
      address: "대구 수성구 동대구로14길 15-6, 2층",
      shop: "business",
    },
    membership: {
      name: "스탠다드",
      package: "6회권",
      date: "2025-01-04 ~",
      count: "5회 / 6회",
      during: "2개월",
    },
    worker: {
      star: "4.5점(9개 리뷰)",
      name: "장규빈",
      mobile: "010-1571-0489",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "서비스 품질",
      machine: "민감고객",
      address: "c/s이력 있음",

      date: "2025.02.21",
      plus: "자가점검키트",
      memo: "필터 교체 후 기기 작동 불안정함. 서비스 품질 신뢰도 낮아짐.",
    },
    payment: {
      service: 99000,
      extra: 0,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
    },
    primemember: true,
  },
]);
// 정산
export const fullSaleList = reactive([
  {
    id: 1,
    number: "ST202305270001",
    workername: "김철수",
    status: "waiting", // 대기중
    tex: 60000, // 수수료
    openModal() {},
    openDetailById(id) {
      console.log(id);
    },

    primemember: true,
    customer: {
      name: "홍길동",
      saleId: "S20230501",
      type: "cleaning",
      period: "2025-04-01 ~ 2025-04-30",
      cleannum: 4,
      totalPrice: 240000,
      plusprice: 0,
      settledAt: "2025-05-10",
    },
    worker: {
      mobile: "010-1234-5678",
    },
  },
  {
    id: 2,
    number: "ST202305270002",
    workername: "이영희",
    status: "done", // 청소완료
    tex: 50000,
    openModal() {},
    openDetailById(id) {
      console.log(id);
    },

    primemember: false,
    customer: {
      name: "박민수",
      saleId: "S20230502",
      type: "bonus",
      period: "2025-04-01 ~ 2025-04-30",
      cleannum: 0,
      totalPrice: 50000,
      plusprice: 50000,
      settledAt: "2025-05-15",
    },
    worker: {
      mobile: "010-9876-5432",
    },
  },
  {
    id: 3,
    number: "ST202305270003",
    workername: "최지훈",
    status: "confirmed", // 확정완료
    tex: 40000,
    openModal() {},
    openDetailById(id) {
      console.log(id);
    },

    primemember: true,
    customer: {
      name: "김하늘",
      saleId: "S20230503",
      type: "cleaning",
      period: "2025-04-01 ~ 2025-04-30",
      cleannum: 3,
      totalPrice: 180000,
      plusprice: 0,
      settledAt: "2025-05-20",
    },
    worker: {
      mobile: "010-1111-2222",
    },
  },
  {
    id: 4,
    number: "ST202305270004",
    workername: "한예진",
    status: "waiting",
    tex: 0,
    openModal() {},
    openDetailById(id) {
      console.log(id);
    },

    primemember: false,
    customer: {
      name: "조민아",
      saleId: "S20230504",
      type: "penalty",
      period: "2025-04-01 ~ 2025-04-30",
      cleannum: 0,
      totalPrice: -30000,
      plusprice: 0,
      settledAt: "2025-05-22",
    },
    worker: {
      mobile: "010-2222-3333",
    },
  },
  {
    id: 5,
    number: "ST202305270005",
    workername: "박지성",
    status: "done",
    tex: 70000,
    openModal() {},
    openDetailById(id) {
      console.log(id);
    },

    primemember: true,
    customer: {
      name: "김유진",
      saleId: "S20230505",
      type: "cleaning",
      period: "2025-04-01 ~ 2025-04-30",
      cleannum: 5,
      totalPrice: 300000,
      plusprice: 0,
      settledAt: "2025-05-18",
    },
    worker: {
      mobile: "010-3333-4444",
    },
  },
  {
    id: 6,
    number: "ST202305270006",
    workername: "이수진",
    status: "confirmed",
    tex: 0,
    openModal() {},
    openDetailById(id) {
      console.log(id);
    },

    primemember: false,
    customer: {
      name: "최민호",
      saleId: "S20230506",
      type: "bonus",
      period: "2025-04-01 ~ 2025-04-30",
      cleannum: 0,
      totalPrice: 40000,
      plusprice: 40000,
      settledAt: "2025-05-23",
    },
    worker: {
      mobile: "010-4444-5555",
    },
  },
  {
    id: 7,
    number: "ST202305270007",
    workername: "김현수",
    status: "waiting",
    tex: 30000,
    openModal() {},
    openDetailById(id) {
      console.log(id);
    },

    primemember: true,
    customer: {
      name: "송민정",
      saleId: "S20230507",
      type: "cleaning",
      period: "2025-04-01 ~ 2025-04-30",
      cleannum: 2,
      totalPrice: 120000,
      plusprice: 0,
      settledAt: "2025-05-19",
    },
    worker: {
      mobile: "010-5555-6666",
    },
  },
  {
    id: 8,
    number: "ST202305270008",
    workername: "오지혜",
    status: "done",
    tex: 25000,
    openModal() {},
    openDetailById(id) {
      console.log(id);
    },

    primemember: false,
    customer: {
      name: "한승우",
      saleId: "S20230508",
      type: "cleaning",
      period: "2025-04-01 ~ 2025-04-30",
      cleannum: 1,
      totalPrice: 60000,
      plusprice: 0,
      settledAt: "2025-05-17",
    },
    worker: {
      mobile: "010-6666-7777",
    },
  },
  {
    id: 9,
    number: "ST202305270009",
    workername: "배수정",
    status: "confirmed",
    tex: 60000,
    openModal() {},
    openDetailById(id) {
      console.log(id);
    },

    primemember: true,
    customer: {
      name: "윤재훈",
      saleId: "S20230509",
      type: "cleaning",
      period: "2025-04-01 ~ 2025-04-30",
      cleannum: 4,
      totalPrice: 240000,
      plusprice: 0,
      settledAt: "2025-05-21",
    },
    worker: {
      mobile: "010-7777-8888",
    },
  },
  {
    id: 10,
    number: "ST202305270010",
    workername: "송지은",
    status: "waiting",
    tex: 0,
    openModal() {},
    openDetailById(id) {
      console.log(id);
    },

    primemember: false,
    customer: {
      name: "김민석",
      saleId: "S20230510",
      type: "penalty",
      period: "2025-04-01 ~ 2025-04-30",
      cleannum: 0,
      totalPrice: -20000,
      plusprice: 0,
      settledAt: "2025-05-24",
    },
    worker: {
      mobile: "010-8888-9999",
    },
  },
  {
    id: 11,
    number: "ST202305270011",
    workername: "윤보라",
    status: "done",
    tex: 50000,
    openModal() {},
    openDetailById(id) {
      console.log(id);
    },

    primemember: true,
    customer: {
      name: "최서연",
      saleId: "S20230511",
      type: "cleaning",
      period: "2025-04-01 ~ 2025-04-30",
      cleannum: 3,
      totalPrice: 180000,
      plusprice: 0,
      settledAt: "2025-05-25",
    },
    worker: {
      mobile: "010-9999-0000",
    },
  },
  {
    id: 12,
    number: "ST202305270012",
    workername: "강민우",
    status: "confirmed",
    tex: 0,
    openModal() {},
    openDetailById(id) {
      console.log(id);
    },

    primemember: false,
    customer: {
      name: "박주희",
      saleId: "S20230512",
      type: "bonus",
      period: "2025-04-01 ~ 2025-04-30",
      cleannum: 0,
      totalPrice: 30000,
      plusprice: 30000,
      settledAt: "2025-05-26",
    },
    worker: {
      mobile: "010-0000-1111",
    },
  },
  {
    id: 13,
    number: "ST202305270013",
    workername: "전지현",
    status: "waiting",
    tex: 40000,
    openModal() {},
    openDetailById(id) {
      console.log(id);
    },

    primemember: true,
    customer: {
      name: "김태형",
      saleId: "S20230513",
      type: "cleaning",
      period: "2025-04-01 ~ 2025-04-30",
      cleannum: 4,
      totalPrice: 240000,
      plusprice: 0,
      settledAt: "2025-05-27",
    },
    worker: {
      mobile: "010-1212-3434",
    },
  },
  {
    id: 14,
    number: "ST202305270014",
    workername: "한소희",
    status: "done",
    tex: 35000,
    openModal() {},
    openDetailById(id) {
      console.log(id);
    },

    primemember: false,
    customer: {
      name: "윤서진",
      saleId: "S20230514",
      type: "cleaning",
      period: "2025-04-01 ~ 2025-04-30",
      cleannum: 2,
      totalPrice: 120000,
      plusprice: 0,
      settledAt: "2025-05-28",
    },
    worker: {
      mobile: "010-3434-5656",
    },
  },
  {
    id: 15,
    number: "ST202305270015",
    workername: "김도현",
    status: "confirmed",
    tex: 55000,
    openModal() {},
    openDetailById(id) {
      console.log(id);
    },

    primemember: true,
    customer: {
      name: "이민정",
      saleId: "S20230515",
      type: "cleaning",
      period: "2025-04-01 ~ 2025-04-30",
      cleannum: 5,
      totalPrice: 300000,
      plusprice: 0,
      settledAt: "2025-05-29",
    },
    worker: {
      mobile: "010-5656-7878",
    },
  },
]);
