import { ref, reactive } from "vue";
export const detailList = [
  {
    id: 1,
    customer: {
      name: "고윤정",
      mobile: "010-1234-1234",
      email: "yunjung@naver.com",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
    },
    membership: {
      name: "호시자키",
      package: "6회권",
      date: "2025-03-17 ~",
      count: "2회 / 6회",
      during: "3개월",
    },
    worker: {
      star: "4.5점(9개 리뷰)",
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: "기타 문의",
      title: "라벨 증정",
      memo: "라벨 안 주고 가셨어요 ㅠㅠ",
      file: null,
    },
    reservinfo: {
      type: "비정기 청소",
      machine: "[호시자키] 250kg 이상 1대",
      address: "대구광역시 중구 중앙대로 77길 22 스타벅스 종로점",
      date: "2025-05-15, 오후 11시 이후",
      plus: "자가점검키트",
      memo: "레포트 문자로 보내주세요",
    },
    payment: {
      service: 210000,
      extra: 4900,
      coupon: 0,
      membershipDiscount: -210000,
      extraDiscount: -4900,
      get total() {
        return (
          this.service +
          this.extra +
          this.coupon +
          this.membershipDiscount +
          this.extraDiscount
        );
      },
    },
  },
  {
    id: 3,
    customer: {
      name: "김카페",
      mobile: "010-1245-1534",
      email: "cafekim@naver.com",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
    },
    membership: {
      name: null,
      date: null,
      count: null,
      during: null,
    },
    worker: {
      star: "4.5점(9개 리뷰)",
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "일회성 청소",
      machine: "[스탠다드] 50kg 미만 1대",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 4층",
      date: "2025-05-22, 오후 2시",
      plus: "자가 점검 키트",
      memo: null,
    },
    payment: {
      service: 99000,
      extra: 4900,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
      get total() {
        return (
          this.service +
          this.extra +
          this.coupon +
          this.membershipDiscount +
          this.extraDiscount
        );
      },
    },
  },
  {
    id: 2,
    customer: {
      name: "김카페",
      mobile: "010-1245-1534",
      email: "cafekim@naver.com",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
    },
    membership: {
      name: null,
      date: null,
      count: null,
      during: null,
    },
    worker: {
      star: "4.5점(9개 리뷰)",
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "일회성 청소",
      machine: "[스탠다드] 50kg 미만 1대",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 4층",
      date: "2025-05-22, 오후 2시",
      plus: null,
      memo: null,
    },
    payment: {
      service: 99000,
      extra: 0,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
      get total() {
        return (
          this.service +
          this.extra +
          this.coupon +
          this.membershipDiscount +
          this.extraDiscount
        );
      },
    },
  },
];
// 예약 내역 데이터
export const reservList = ref([
  {
    id: 1,
    number: "BING-2025-001",
    status: "confirmed",
    date: "2025-03-18, 오후 11시 이후",
    memo: "라벨 부착해주세요.",
    price: 0,
    reservdate: "2025.03.17(월) 14:00",
  },
  {
    id: 2,
    number: "BING-2025-002",
    status: "assigned",
    date: "2025-05-15, 오후 11시 이후",
    memo: "레포트 문자로 보내주세요",
    price: 0,
    reservdate: "2025.04.30(수) 16:00",
  },

  {
    id: 3,
    number: "BING-2025-003",
    status: "waiting",
    date: "2025-06-18, 오후 11시 이후",
    memo: "세제 신청했어요 ~ ^^",
    price: 0,
    reservdate: "2025.06.17(화) 14:00",
  },
]);

// 전체 테이블 데이터
export const fullReservationList = reactive([
  {
    id: 1,
    number: "BING-2025-001",
    status: "confirmed",
    date: "2025-03-18, 오후 11시 이후",
    memo: "라벨 부착해주세요.",
    price: 0,
    reservdate: "2025.03.17(월) 14:00",
    customer: {
      name: "고윤정",
      mobile: "010-1234-1234",
      email: "yunjung@naver.com",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
      shop: "business",
    },
    membership: {
      name: "호시자키",
      package: "6회권",
      date: "2025-03-17 ~",
      count: "2회 / 6회",
      during: "3개월",
    },
    worker: {
      star: "4.5점(9개 리뷰)",
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
      gender: "female",
      health: false,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: "기타 문의",
      title: "라벨 증정",
      memo: "라벨 안 주고 가셨어요 ㅠㅠ",
      file: null,
    },
    reservinfo: {
      type: "비정기 청소",
      machine: "[호시자키] 250kg 이상 1대",
      address: "대구광역시 중구 중앙대로 77길 22 스타벅스 종로점",
      date: "2025.05.30",
      time: "오후 11시 이후",
      plus: "자가점검키트",
      memo: "레포트 문자로 보내주세요",
    },
    payment: {
      service: 210000,
      extra: 4900,
      coupon: 0,
      membershipDiscount: -210000,
      extraDiscount: -4900,
    },
    primemember: true,
  },
  {
    id: 2,
    number: "BING-2025-002",
    status: "waiting",
    date: "2025-06-18, 오후 11시 이후",
    memo: "세제 신청했어요 ~ ^^",
    price: 0,
    reservdate: "2025.06.17(화) 14:00",
    customer: {
      name: "김카페",
      mobile: "010-1245-1534",
      email: "cafekim@naver.com",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
      shop: "personal",
    },
    membership: {
      name: null,
      date: null,
      count: null,
      during: null,
    },
    worker: {
      star: "4.5점(9개 리뷰)",
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "일회성 청소",
      machine: "[디럭스] 100~200kg 1대",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 4층",
      date: "2025.05.31",
      time: "오후 11시 이후",
      plus: "자가 점검 키트",
      memo: null,
    },
    payment: {
      service: 99000,
      extra: 4900,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
    },
    primemember: false,
  },
  {
    id: 3,
    number: "BING-2025-003",
    status: "assigned",
    date: "2025-05-15, 오후 11시 이후",
    memo: "레포트 문자로 보내주세요",
    price: 0,
    reservdate: "2025.04.30(수) 16:00",
    customer: {
      name: "김카페",
      mobile: "010-1245-1534",
      email: "cafekim@naver.com",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
      shop: "personal",
    },
    membership: {
      name: null,
      date: null,
      count: null,
      during: null,
    },
    worker: {
      star: "4.5점(9개 리뷰)",
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "일회성 청소",
      machine: "[스탠다드] 50kg 미만 1대",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 4층",
      date: "2025.07.12",
      time: "오후 2시 이후",
      plus: null,
      memo: null,
    },
    payment: {
      service: 99000,
      extra: 0,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
    },
    primemember: false,
  },
  {
    id: 4,
    number: "BING-2025-004",
    status: "done",
    date: "2025-03-28, 오후 7시 이후",
    memo: "라벨 부착해주세요.",
    price: 0,
    reservdate: "2025-05-28",
    customer: {
      name: "정유진",
      mobile: "010-1234-1234",
      email: "정유진@bingfree.co.kr",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
      shop: "personal",
    },
    membership: {
      name: "스탠다드",
      package: "6회권",
      date: "2025-01-25 ~",
      count: "3회 / 6회",
      during: "1개월",
    },
    worker: {
      star: "4.5점(9개 리뷰)",
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: "기타 문의",
      title: "라벨 증정",
      memo: "라벨 안 주고 가셨어요 ㅠㅠ",
      file: null,
    },
    reservinfo: {
      type: "비정기 청소",
      machine: "[호시자키] 250kg 이상 1대",
      address: "대구광역시 중구 중앙대로 77길 22 스타벅스 종로점",
      date: "2025.02.22",
      time: "13:00",
      plus: "자가점검키트",
      memo: "레포트 문자로 보내주세요",
    },
    payment: {
      service: 210000,
      extra: 4900,
      coupon: 0,
      membershipDiscount: -210000,
      extraDiscount: -4900,
    },
    primemember: true,
  },
  {
    id: 5,
    number: "BING-2025-005",
    status: "waiting",
    date: "2025-01-29, 오후 9시 이후",
    memo: "세제 신청했어요 ~ ^^",
    price: 0,
    reservdate: "2025-02-21",
    customer: {
      name: "박서준",
      mobile: "010-1245-1534",
      email: "박서준@bingfree.co.kr",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
      shop: "personal",
    },
    membership: {
      name: null,
      date: null,
      count: null,
      during: null,
    },
    worker: {
      star: "4.5점(9개 리뷰)",
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "일회성 청소",
      machine: "[프리미엄] 200Kg이상 2대",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 4층",
      date: "2025.08.22",
      time: "오후 4시 이후",
      plus: "자가 점검 키트",
      memo: null,
    },
    payment: {
      service: 99000,
      extra: 4900,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
    },
    primemember: false,
  },
  {
    id: 6,
    number: "BING-2025-006",
    status: "done",
    date: "2025-02-22, 오후 10시 이후",
    memo: "레포트 문자로 보내주세요",
    price: 0,
    reservdate: "2025-03-04",
    customer: {
      name: "최지은",
      mobile: "010-1245-1534",
      email: "최지은@bingfree.co.kr",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
      shop: "personal",
    },
    membership: {
      name: null,
      date: null,
      count: null,
      during: null,
    },
    worker: {
      star: "4.5점(9개 리뷰)",
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "일회성 청소",
      machine: "[스탠다드] 50kg 미만 1대",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 4층",
      date: "2025.05.30",
      time: "15시",
      plus: null,
      memo: null,
    },
    payment: {
      service: 99000,
      extra: 0,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
    },
    primemember: false,
  },
  {
    id: 7,
    number: "BING-2025-007",
    status: "confirmed",
    date: "2025-02-12, 오후 3시 이후",
    memo: "라벨 부착해주세요.",
    price: 0,
    reservdate: "2025-01-20",
    customer: {
      name: "이동건",
      mobile: "010-1234-1234",
      email: "이동건@bingfree.co.kr",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
      shop: "business",
    },
    membership: {
      name: "스탠다드",
      package: "12회권",
      date: "2025-01-26 ~",
      count: "5회 / 6회",
      during: "3개월",
    },
    worker: {
      star: "4.5점(9개 리뷰)",
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: "기타 문의",
      title: "라벨 증정",
      memo: "라벨 안 주고 가셨어요 ㅠㅠ",
      file: null,
    },
    reservinfo: {
      type: "비정기 청소",
      machine: "[호시자키] 250kg 이상 1대",
      address: "대구광역시 중구 중앙대로 77길 22 스타벅스 종로점",
      date: "2025.07.12",
      time: "오전 11시~12시",
      plus: "자가점검키트",
      memo: "레포트 문자로 보내주세요",
    },
    payment: {
      service: 210000,
      extra: 4900,
      coupon: 0,
      membershipDiscount: -210000,
      extraDiscount: -4900,
    },
    primemember: true,
  },
  {
    id: 8,
    number: "BING-2025-008",
    status: "waiting",
    date: "2025-01-05, 오후 1시 이후",
    memo: "세제 신청했어요 ~ ^^",
    price: 0,
    reservdate: "2025-03-21",
    customer: {
      name: "장민호",
      mobile: "010-1245-1534",
      email: "장민호@bingfree.co.kr",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
      shop: "business",
    },
    membership: {
      name: "스탠다드",
      package: "12회권",
      date: "2025-03-13 ~",
      count: "3회 / 6회",
      during: "6개월",
    },
    worker: {
      star: "4.5점(9개 리뷰)",
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "일회성 청소",
      machine: "[스탠다드] 50kg 미만 1대",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 4층",
      date: "2025.09.22",
      time: "오후 11시 이후",
      plus: "자가 점검 키트",
      memo: null,
    },
    payment: {
      service: 99000,
      extra: 4900,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
    },
    primemember: true,
  },
  {
    id: 9,
    number: "BING-2025-009",
    status: "done",
    date: "2025-02-09, 오후 11시 이후",
    memo: "레포트 문자로 보내주세요",
    price: 0,
    reservdate: "2025-02-19",
    customer: {
      name: "하윤아",
      mobile: "010-1245-1534",
      email: "하윤아@bingfree.co.kr",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
      shop: "personal",
    },
    membership: {
      name: null,
      date: null,
      count: null,
      during: null,
    },
    worker: {
      star: "4.5점(9개 리뷰)",
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "일회성 청소",
      machine: "[스탠다드] 50kg 미만 1대",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 4층",
      date: "2025.03.22",
      time: "21시 이후",
      plus: null,
      memo: null,
    },
    payment: {
      service: 99000,
      extra: 0,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
    },
    primemember: false,
  },
  {
    id: 10,
    number: "BING-2025-010",
    status: "confirmed",
    date: "2025-03-26, 오후 3시 이후",
    memo: "라벨 부착해주세요.",
    price: 0,
    reservdate: "2025-02-11",
    customer: {
      name: "문채원",
      mobile: "010-1234-1234",
      email: "문채원@bingfree.co.kr",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
      shop: "business",
    },
    membership: {
      name: "스탠다드",
      package: "6회권",
      date: "2025-01-22 ~",
      count: "6회 / 6회",
      during: "3개월",
    },
    worker: {
      star: "4.5점(9개 리뷰)",
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: "기타 문의",
      title: "라벨 증정",
      memo: "라벨 안 주고 가셨어요 ㅠㅠ",
      file: null,
    },
    reservinfo: {
      type: "비정기 청소",
      machine: "[호시자키] 250kg 이상 1대",
      address: "대구광역시 중구 중앙대로 77길 22 스타벅스 종로점",
      date: "2025.05.24",
      time: "오후 11시 이후",
      plus: "자가점검키트",
      memo: "레포트 문자로 보내주세요",
    },
    payment: {
      service: 210000,
      extra: 4900,
      coupon: 0,
      membershipDiscount: -210000,
      extraDiscount: -4900,
    },
    primemember: true,
  },
  {
    id: 11,
    number: "BING-2025-011",
    status: "waiting",
    date: "2025-01-27, 오후 5시 이후",
    memo: "세제 신청했어요 ~ ^^",
    price: 0,
    reservdate: "2025-08-13",
    customer: {
      name: "윤도현",
      mobile: "010-1245-1534",
      email: "윤도현@bingfree.co.kr",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
      shop: "business",
    },
    membership: {
      name: "스탠다드",
      package: "6회권",
      date: "2025-02-04 ~",
      count: "3회 / 6회",
      during: "1개월",
    },
    worker: {
      star: "4.5점(9개 리뷰)",
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "일회성 청소",
      machine: "[디럭스] 100~200kg 1대",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 4층",
      date: "2025.11.22",
      time: "오후 11시 이후",
      plus: "자가 점검 키트",
      memo: null,
    },
    payment: {
      service: 99000,
      extra: 4900,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
    },
    primemember: true,
  },
  {
    id: 12,
    number: "BING-2025-012",
    status: "assigned",
    date: "2025-01-20, 오후 8시 이후",
    memo: "레포트 문자로 보내주세요",
    price: 0,
    reservdate: "2025-08-27",
    customer: {
      name: "백예린",
      mobile: "010-1245-1534",
      email: "백예린@bingfree.co.kr",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
      shop: "personal",
    },
    membership: {
      name: null,
      date: null,
      count: null,
      during: null,
    },
    worker: {
      star: "4.5점(9개 리뷰)",
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "일회성 청소",
      machine: "[스탠다드] 50kg 미만 1대",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 4층",
      date: "2025.12.21",
      time: "오후 1시 이후",
      plus: null,
      memo: null,
    },
    payment: {
      service: 99000,
      extra: 0,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
    },
    primemember: false,
  },
  {
    id: 13,
    number: "BING-2025-013",
    status: "confirmed",
    date: "2025-01-09, 오후 10시 이후",
    memo: "라벨 부착해주세요.",
    price: 0,
    reservdate: "2025-06-01",
    customer: {
      name: "서지호",
      mobile: "010-1234-1234",
      email: "서지호@bingfree.co.kr",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
      shop: "business",
    },
    membership: {
      name: "스탠다드",
      package: "12회권",
      date: "2025-03-09 ~",
      count: "1회 / 6회",
      during: "3개월",
    },
    worker: {
      star: "4.5점(9개 리뷰)",
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: "기타 문의",
      title: "라벨 증정",
      memo: "라벨 안 주고 가셨어요 ㅠㅠ",
      file: null,
    },
    reservinfo: {
      type: "비정기 청소",
      machine: "[호시자키] 250kg 이상 1대",
      address: "대구광역시 중구 중앙대로 77길 22 스타벅스 종로점",
      date: "2025.08.22",
      time: "오후 11시 이후",
      plus: "자가점검키트",
      memo: "레포트 문자로 보내주세요",
    },
    payment: {
      service: 210000,
      extra: 4900,
      coupon: 0,
      membershipDiscount: -210000,
      extraDiscount: -4900,
    },
    primemember: true,
  },
  {
    id: 14,
    number: "BING-2025-014",
    status: "waiting",
    date: "2025-01-18, 오후 11시 이후",
    memo: "세제 신청했어요 ~ ^^",
    price: 0,
    reservdate: "2025-03-06",
    customer: {
      name: "김지수",
      mobile: "010-1245-1534",
      email: "김지수@bingfree.co.kr",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
      shop: "personal",
    },
    membership: {
      name: null,
      date: null,
      count: null,
      during: null,
    },
    worker: {
      star: "4.5점(9개 리뷰)",
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "일회성 청소",
      machine: "[스탠다드] 50kg 미만 1대",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 4층",
      date: "2025.05.30",
      time: "오후 11시 이후",
      plus: "자가 점검 키트",
      memo: null,
    },
    payment: {
      service: 99000,
      extra: 4900,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
    },
    primemember: false,
  },
  {
    id: 15,
    number: "BING-2025-015",
    status: "assigned",
    date: "2025-02-15, 오후 3시 이후",
    memo: "레포트 문자로 보내주세요",
    price: 0,
    reservdate: "2025-02-26",
    customer: {
      name: "강다현",
      mobile: "010-1245-1534",
      email: "강다현@bingfree.co.kr",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
      shop: "business",
    },
    membership: {
      name: "스탠다드",
      package: "6회권",
      date: "2025-01-04 ~",
      count: "5회 / 6회",
      during: "2개월",
    },
    worker: {
      star: "4.5점(9개 리뷰)",
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "일회성 청소",
      machine: "[스탠다드] 50kg 미만 1대",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 4층",
      date: "2025-08-22, 오후 2시",
      plus: null,
      memo: null,
    },
    payment: {
      service: 99000,
      extra: 0,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
    },
    primemember: true,
  },
]);

// 지역 선택 데이터
export const koreaLocations = reactive({
  서울특별시: [
    "강남구",
    "강동구",
    "강북구",
    "강서구",
    "관악구",
    "광진구",
    "구로구",
    "금천구",
    "노원구",
    "도봉구",
    "동대문구",
    "동작구",
    "마포구",
    "서대문구",
    "서초구",
    "성동구",
    "성북구",
    "송파구",
    "양천구",
    "영등포구",
    "용산구",
    "은평구",
    "종로구",
    "중구",
    "중랑구",
  ],
  부산광역시: [
    "강서구",
    "금정구",
    "기장군",
    "남구",
    "동구",
    "동래구",
    "부산진구",
    "북구",
    "사상구",
    "사하구",
    "서구",
    "수영구",
    "연제구",
    "영도구",
    "중구",
    "해운대구",
  ],
  대구광역시: [
    "남구",
    "달서구",
    "달성군",
    "동구",
    "북구",
    "서구",
    "수성구",
    "중구",
  ],
  인천광역시: [
    "강화군",
    "계양구",
    "남동구",
    "동구",
    "미추홀구",
    "부평구",
    "서구",
    "연수구",
    "옹진군",
    "중구",
  ],
  광주광역시: ["광산구", "남구", "동구", "북구", "서구"],
  대전광역시: ["대덕구", "동구", "서구", "유성구", "중구"],
  울산광역시: ["남구", "동구", "북구", "울주군", "중구"],
  세종특별자치시: ["세종시"],
  경기도: [
    "가평군",
    "고양시",
    "과천시",
    "광명시",
    "광주시",
    "구리시",
    "군포시",
    "김포시",
    "남양주시",
    "동두천시",
    "부천시",
    "성남시",
    "수원시",
    "시흥시",
    "안산시",
    "안성시",
    "안양시",
    "양주시",
    "양평군",
    "여주시",
    "연천군",
    "오산시",
    "용인시",
    "의왕시",
    "의정부시",
    "이천시",
    "파주시",
    "평택시",
    "포천시",
    "하남시",
    "화성시",
  ],
  강원도: [
    "강릉시",
    "고성군",
    "동해시",
    "삼척시",
    "속초시",
    "양구군",
    "양양군",
    "영월군",
    "원주시",
    "인제군",
    "정선군",
    "철원군",
    "춘천시",
    "태백시",
    "평창군",
    "홍천군",
    "화천군",
    "횡성군",
  ],
  충청북도: [
    "괴산군",
    "단양군",
    "보은군",
    "영동군",
    "옥천군",
    "음성군",
    "제천시",
    "증평군",
    "진천군",
    "청주시",
    "충주시",
  ],
  충청남도: [
    "계룡시",
    "공주시",
    "금산군",
    "논산시",
    "당진시",
    "보령시",
    "부여군",
    "서산시",
    "서천군",
    "아산시",
    "예산군",
    "천안시",
    "청양군",
    "태안군",
    "홍성군",
  ],
  전라북도: [
    "고창군",
    "군산시",
    "김제시",
    "남원시",
    "무주군",
    "부안군",
    "순창군",
    "완주군",
    "익산시",
    "임실군",
    "장수군",
    "전주시",
    "정읍시",
    "진안군",
  ],
  전라남도: [
    "강진군",
    "고흥군",
    "곡성군",
    "광양시",
    "구례군",
    "나주시",
    "담양군",
    "목포시",
    "무안군",
    "보성군",
    "순천시",
    "신안군",
    "여수시",
    "영광군",
    "영암군",
    "완도군",
    "장성군",
    "장흥군",
    "진도군",
    "함평군",
    "해남군",
    "화순군",
  ],
  경상북도: [
    "경산시",
    "경주시",
    "고령군",
    "구미시",
    "군위군",
    "김천시",
    "문경시",
    "봉화군",
    "상주시",
    "성주군",
    "안동시",
    "영덕군",
    "영양군",
    "영주시",
    "영천시",
    "예천군",
    "울릉군",
    "울진군",
    "의성군",
    "청도군",
    "청송군",
    "칠곡군",
    "포항시",
  ],
  경상남도: [
    "거제시",
    "거창군",
    "고성군",
    "김해시",
    "남해군",
    "밀양시",
    "사천시",
    "산청군",
    "양산시",
    "의령군",
    "진주시",
    "창녕군",
    "창원시",
    "통영시",
    "하동군",
    "함안군",
    "함양군",
    "합천군",
  ],
  제주특별자치도: ["서귀포시", "제주시"],
});

// 테이블 헤더 데이터
export const TableHeaders = [
  { key: "item", label: "결제 내역" },
  { key: "amount", label: "결제금액" },
  { key: "date", label: "결제일" },
  { key: "period", label: "이용 기간" },
  { key: "status", label: "상태" },
  { key: "receipt", label: "영수증" },
];

// 테이블 내용 데이터
export const TableData = [
  {
    item: "호시자키(250kg~) 6회권",
    amount: "1,134,000원",
    date: "2025.03.17 14:00",
    period: "2025.03.17 ~ 2026.03.17",
    status: "결제 완료",
    receipt: "영수증 보기",
    receiptUrl: "#",
  },
];
