import { ref, reactive } from "vue";
export const detailList = [
  {
    id: 1,
    customer: {
      name: "고윤정",
      mobile: "010-1234-1234",
      email: "yunjung@naver.com",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
    },
    membership: {
      name: "호시자키",
      package: "6회권",
      date: "2025-03-17 ~",
      count: "2회 / 6회",
      during: "3개월",
    },
    worker: {
      star: "4.5점(9개 리뷰)",
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: "기타 문의",
      title: "라벨 증정",
      memo: "라벨 안 주고 가셨어요 ㅠㅠ",
      file: null,
    },
    reservinfo: {
      type: "비정기 청소",
      machine: "[호시자키] 250kg 이상 1대",
      address: "대구광역시 중구 중앙대로 77길 22 스타벅스 종로점",
      date: "2025-05-15, 오후 11시 이후",
      plus: "자가점검키트",
      memo: "레포트 문자로 보내주세요",
    },
    payment: {
      service: 210000,
      extra: 4900,
      coupon: 0,
      membershipDiscount: -210000,
      extraDiscount: -4900,
      get total() {
        return this.service + this.extra + this.coupon + this.membershipDiscount + this.extraDiscount;
      },
    },
  },
  {
    id: 3,
    customer: {
      name: "김카페",
      mobile: "010-1245-1534",
      email: "cafekim@naver.com",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
    },
    membership: {
      name: null,
      date: null,
      count: null,
      during: null,
    },
    worker: {
      star: "4.5점(9개 리뷰)",
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "일회성 청소",
      machine: "[스탠다드] 50kg 미만 1대",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 4층",
      date: "2025-05-22, 오후 2시",
      plus: "자가 점검 키트",
      memo: null,
    },
    payment: {
      service: 99000,
      extra: 4900,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
      get total() {
        return this.service + this.extra + this.coupon + this.membershipDiscount + this.extraDiscount;
      },
    },
  },
  {
    id: 2,
    customer: {
      name: "김카페",
      mobile: "010-1245-1534",
      email: "cafekim@naver.com",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
    },
    membership: {
      name: null,
      date: null,
      count: null,
      during: null,
    },
    worker: {
      star: "4.5점(9개 리뷰)",
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "일회성 청소",
      machine: "[스탠다드] 50kg 미만 1대",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 4층",
      date: "2025-05-22, 오후 2시",
      plus: null,
      memo: null,
    },
    payment: {
      service: 99000,
      extra: 0,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
      get total() {
        return this.service + this.extra + this.coupon + this.membershipDiscount + this.extraDiscount;
      },
    },
  },
];
// 예약 내역 데이터
export const reservList = ref([
  {
    id: 1,
    number: "BING-2025-001",
    status: "confirmed",
    date: "2025-03-18, 오후 11시 이후",
    memo: "라벨 부착해주세요.",
    price: 0,
    reservdate: "2025.03.17(월) 14:00",
  },
  {
    id: 2,
    number: "BING-2025-002",
    status: "assigned",
    date: "2025-05-15, 오후 11시 이후",
    memo: "레포트 문자로 보내주세요",
    price: 0,
    reservdate: "2025.04.30(수) 16:00",
  },

  {
    id: 3,
    number: "BING-2025-003",
    status: "waiting",
    date: "2025-06-18, 오후 11시 이후",
    memo: "세제 신청했어요 ~ ^^",
    price: 0,
    reservdate: "2025.06.17(화) 14:00",
  },
]);

// 전체 테이블 데이터
export const fullReservationList = reactive([
  {
    id: 1,
    number: "BING-2025-001",
    status: "confirmed",
    date: "2025-03-18, 오후 11시 이후",
    memo: "라벨 부착해주세요.",
    price: 0,
    reservdate: "2025.03.17(월) 14:00",
    customer: {
      name: "고윤정",
      mobile: "010-1234-1234",
      email: "yunjung@naver.com",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
      shop: "business",
    },
    membership: {
      name: "호시자키",
      package: "6회권",
      date: "2025-03-17 ~",
      count: "2회 / 6회",
      during: "3개월",
    },
    worker: {
      bingnb: "bing01",
      star: "4.5점(9개 리뷰)",
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
      gender: "female",
      health: false,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: "기타 문의",
      title: "라벨 증정",
      memo: "라벨 안 주고 가셨어요 ㅠㅠ",
      file: null,
    },
    reservinfo: {
      type: "비정기 청소",
      machine: "[호시자키] 250kg 이상 1대",
      address: "대구광역시 중구 중앙대로 77길 22 스타벅스 종로점",
      date: "2025.05.30",
      time: "오후 11시 이후",
      plus: "자가점검키트",
      memo: "레포트 문자로 보내주세요",
    },
    payment: {
      service: 210000,
      extra: 4900,
      coupon: 0,
      membershipDiscount: -210000,
      extraDiscount: -4900,
    },
    primemember: true,
  },
  {
    id: 2,
    number: "BING-2025-002",
    status: "waiting",
    date: "2025-06-18, 오후 11시 이후",
    memo: "세제 신청했어요 ~ ^^",
    price: 0,
    reservdate: "2025.06.17(화) 14:00",
    customer: {
      name: "김카페",
      mobile: "010-1245-1534",
      email: "cafekim@naver.com",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
      shop: "personal",
    },
    membership: {
      name: null,
      date: null,
      count: null,
      during: null,
    },
    worker: {
      bingnb: "bing02",
      star: "4.5점(9개 리뷰)",
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "일회성 청소",
      machine: "[디럭스] 100~200kg 1대",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 4층",
      date: "2025.05.31",
      time: "오후 11시 이후",
      plus: "자가 점검 키트",
      memo: null,
    },
    payment: {
      service: 150000,
      extra: 4900,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
    },
    primemember: false,
  },
  {
    id: 3,
    number: "BING-2025-003",
    status: "assigned",
    date: "2025-05-15, 오후 11시 이후",
    memo: "레포트 문자로 보내주세요",
    price: 0,
    reservdate: "2025.04.30(수) 16:00",
    customer: {
      name: "김카페",
      mobile: "010-1245-1534",
      email: "cafekim@naver.com",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
      shop: "personal",
    },
    membership: {
      name: null,
      date: null,
      count: null,
      during: null,
    },
    worker: {
      bingnb: "bing03",
      star: "4.5점(9개 리뷰)",
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "일회성 청소",
      machine: "[스탠다드] 50kg 미만 1대",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 4층",
      date: "2025.07.12",
      time: "오후 2시 이후",
      plus: null,
      memo: null,
    },
    payment: {
      service: 99000,
      extra: 0,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
    },
    primemember: false,
  },
  {
    id: 4,
    number: "BING-2025-004",
    status: "done",
    date: "2025-03-28, 오후 7시 이후",
    memo: "라벨 부착해주세요.",
    price: 0,
    reservdate: "2025-05-28",
    customer: {
      name: "정유진",
      mobile: "010-1234-1234",
      email: "정유진@bingfree.co.kr",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
      shop: "personal",
    },
    membership: {
      name: "스탠다드",
      package: "6회권",
      date: "2025-01-25 ~",
      count: "3회 / 6회",
      during: "1개월",
    },
    worker: {
      bingnb: "bing04",
      star: "4.5점(9개 리뷰)",
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: "기타 문의",
      title: "라벨 증정",
      memo: "라벨 안 주고 가셨어요 ㅠㅠ",
      file: null,
    },
    reservinfo: {
      type: "비정기 청소",
      machine: "[호시자키] 250kg 이상 1대",
      address: "대구광역시 중구 중앙대로 77길 22 스타벅스 종로점",
      date: "2025.02.22",
      time: "13:00",
      plus: "자가점검키트",
      memo: "레포트 문자로 보내주세요",
    },
    payment: {
      service: 210000,
      extra: 4900,
      coupon: 0,
      membershipDiscount: -210000,
      extraDiscount: -4900,
    },
    primemember: true,
  },
  {
    id: 5,
    number: "BING-2025-005",
    status: "waiting",
    date: "2025-01-29, 오후 9시 이후",
    memo: "세제 신청했어요 ~ ^^",
    price: 0,
    reservdate: "2025-02-21",
    customer: {
      name: "박서준",
      mobile: "010-1245-1534",
      email: "박서준@bingfree.co.kr",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
      shop: "personal",
    },
    membership: {
      name: null,
      date: null,
      count: null,
      during: null,
    },
    worker: {
      bingnb: "bing05",
      star: "4.5점(9개 리뷰)",
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "일회성 청소",
      machine: "[프리미엄] 200Kg이상 2대",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 4층",
      date: "2025.08.22",
      time: "오후 4시 이후",
      plus: "자가 점검 키트",
      memo: null,
    },
    payment: {
      service: 170000,
      extra: 0,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
    },
    primemember: false,
  },
  {
    id: 6,
    number: "BING-2025-006",
    status: "done",
    date: "2025-02-22, 오후 10시 이후",
    memo: "레포트 문자로 보내주세요",
    price: 0,
    reservdate: "2025-03-04",
    customer: {
      name: "최지은",
      mobile: "010-1245-1534",
      email: "최지은@bingfree.co.kr",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
      shop: "personal",
    },
    membership: {
      name: null,
      date: null,
      count: null,
      during: null,
    },
    worker: {
      bingnb: "bing06",
      star: "4.5점(9개 리뷰)",
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "일회성 청소",
      machine: "[스탠다드] 50kg 미만 1대",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 4층",
      date: "2025.05.30",
      time: "15시",
      plus: null,
      memo: null,
    },
    payment: {
      service: 99000,
      extra: 0,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
    },
    primemember: false,
  },
  {
    id: 7,
    number: "BING-2025-007",
    status: "confirmed",
    date: "2025-02-12, 오후 3시 이후",
    memo: "라벨 부착해주세요.",
    price: 0,
    reservdate: "2025-01-20",
    customer: {
      name: "이동건",
      mobile: "010-1234-1234",
      email: "이동건@bingfree.co.kr",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
      shop: "business",
    },
    membership: {
      name: "스탠다드",
      package: "12회권",
      date: "2025-01-26 ~",
      count: "5회 / 6회",
      during: "3개월",
    },
    worker: {
      bingnb: "bing07",
      star: "4.5점(9개 리뷰)",
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: "기타 문의",
      title: "라벨 증정",
      memo: "라벨 안 주고 가셨어요 ㅠㅠ",
      file: null,
    },
    reservinfo: {
      type: "비정기 청소",
      machine: "[호시자키] 250kg 이상 1대",
      address: "대구광역시 중구 중앙대로 77길 22 스타벅스 종로점",
      date: "2025.07.12",
      time: "오전 11시~12시",
      plus: "자가점검키트",
      memo: "레포트 문자로 보내주세요",
    },
    payment: {
      service: 210000,
      extra: 4900,
      coupon: 0,
      membershipDiscount: -210000,
      extraDiscount: -4900,
    },
    primemember: true,
  },
  {
    id: 8,
    number: "BING-2025-008",
    status: "waiting",
    date: "2025-01-05, 오후 1시 이후",
    memo: "세제 신청했어요 ~ ^^",
    price: 0,
    reservdate: "2025-03-21",
    customer: {
      name: "장민호",
      mobile: "010-1245-1534",
      email: "장민호@bingfree.co.kr",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
      shop: "business",
    },
    membership: {
      name: "스탠다드",
      package: "12회권",
      date: "2025-03-13 ~",
      count: "3회 / 6회",
      during: "6개월",
    },
    worker: {
      bingnb: "bing08",
      star: "4.5점(9개 리뷰)",
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "일회성 청소",
      machine: "[스탠다드] 50kg 미만 1대",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 4층",
      date: "2025.09.22",
      time: "오후 11시 이후",
      plus: "자가 점검 키트",
      memo: null,
    },
    payment: {
      service: 99000,
      extra: 4900,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
    },
    primemember: true,
  },
  {
    id: 9,
    number: "BING-2025-009",
    status: "done",
    date: "2025-02-09, 오후 11시 이후",
    memo: "레포트 문자로 보내주세요",
    price: 0,
    reservdate: "2025-02-19",
    customer: {
      name: "하윤아",
      mobile: "010-1245-1534",
      email: "하윤아@bingfree.co.kr",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
      shop: "personal",
    },
    membership: {
      name: null,
      date: null,
      count: null,
      during: null,
    },
    worker: {
      bingnb: "bing09",
      star: "4.5점(9개 리뷰)",
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "일회성 청소",
      machine: "[스탠다드] 50kg 미만 1대",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 4층",
      date: "2025.03.22",
      time: "21시 이후",
      plus: null,
      memo: null,
    },
    payment: {
      service: 99000,
      extra: 0,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
    },
    primemember: false,
  },
  {
    id: 10,
    number: "BING-2025-010",
    status: "confirmed",
    date: "2025-03-26, 오후 3시 이후",
    memo: "라벨 부착해주세요.",
    price: 0,
    reservdate: "2025-02-11",
    customer: {
      name: "문채원",
      mobile: "010-1234-1234",
      email: "문채원@bingfree.co.kr",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
      shop: "business",
    },
    membership: {
      name: "스탠다드",
      package: "6회권",
      date: "2025-01-22 ~",
      count: "6회 / 6회",
      during: "3개월",
    },
    worker: {
      bingnb: "bing10",
      star: "4.5점(9개 리뷰)",
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: "기타 문의",
      title: "라벨 증정",
      memo: "라벨 안 주고 가셨어요 ㅠㅠ",
      file: null,
    },
    reservinfo: {
      type: "비정기 청소",
      machine: "[호시자키] 250kg 이상 1대",
      address: "대구광역시 중구 중앙대로 77길 22 스타벅스 종로점",
      date: "2025.05.24",
      time: "오후 11시 이후",
      plus: "자가점검키트",
      memo: "레포트 문자로 보내주세요",
    },
    payment: {
      service: 210000,
      extra: 4900,
      coupon: 0,
      membershipDiscount: -210000,
      extraDiscount: -4900,
    },
    primemember: true,
  },
  {
    id: 11,
    number: "BING-2025-011",
    status: "waiting",
    date: "2025-01-27, 오후 5시 이후",
    memo: "세제 신청했어요 ~ ^^",
    price: 0,
    reservdate: "2025-08-13",
    customer: {
      name: "윤도현",
      mobile: "010-1245-1534",
      email: "윤도현@bingfree.co.kr",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
      shop: "business",
    },
    membership: {
      name: "스탠다드",
      package: "6회권",
      date: "2025-02-04 ~",
      count: "3회 / 6회",
      during: "1개월",
    },
    worker: {
      bingnb: "bing11",
      star: "4.5점(9개 리뷰)",
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "일회성 청소",
      machine: "[디럭스] 100~200kg 1대",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 4층",
      date: "2025.11.22",
      time: "오후 11시 이후",
      plus: "자가 점검 키트",
      memo: null,
    },
    payment: {
      service: 150000,
      extra: 0,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
    },
    primemember: true,
  },
  {
    id: 12,
    number: "BING-2025-012",
    status: "assigned",
    date: "2025-01-20, 오후 8시 이후",
    memo: "레포트 문자로 보내주세요",
    price: 0,
    reservdate: "2025-08-27",
    customer: {
      name: "백예린",
      mobile: "010-1245-1534",
      email: "백예린@bingfree.co.kr",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
      shop: "personal",
    },
    membership: {
      name: null,
      date: null,
      count: null,
      during: null,
    },
    worker: {
      bingnb: "bing12",
      star: "4.5점(9개 리뷰)",
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "일회성 청소",
      machine: "[스탠다드] 50kg 미만 1대",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 4층",
      date: "2025.12.21",
      time: "오후 1시 이후",
      plus: null,
      memo: null,
    },
    payment: {
      service: 99000,
      extra: 0,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
    },
    primemember: false,
  },
  {
    id: 13,
    number: "BING-2025-013",
    status: "confirmed",
    date: "2025-01-09, 오후 10시 이후",
    memo: "라벨 부착해주세요.",
    price: 0,
    reservdate: "2025-06-01",
    customer: {
      name: "서지호",
      mobile: "010-1234-1234",
      email: "서지호@bingfree.co.kr",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
      shop: "business",
    },
    membership: {
      name: "스탠다드",
      package: "12회권",
      date: "2025-03-09 ~",
      count: "1회 / 6회",
      during: "3개월",
    },
    worker: {
      bingnb: "bing13",
      star: "4.5점(9개 리뷰)",
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: "기타 문의",
      title: "라벨 증정",
      memo: "라벨 안 주고 가셨어요 ㅠㅠ",
      file: null,
    },
    reservinfo: {
      type: "비정기 청소",
      machine: "[호시자키] 250kg 이상 1대",
      address: "대구광역시 중구 중앙대로 77길 22 스타벅스 종로점",
      date: "2025.08.22",
      time: "오후 11시 이후",
      plus: "자가점검키트",
      memo: "레포트 문자로 보내주세요",
    },
    payment: {
      service: 210000,
      extra: 4900,
      coupon: 0,
      membershipDiscount: -210000,
      extraDiscount: -4900,
    },
    primemember: true,
  },
  {
    id: 14,
    number: "BING-2025-014",
    status: "waiting",
    date: "2025-01-18, 오후 11시 이후",
    memo: "세제 신청했어요 ~ ^^",
    price: 0,
    reservdate: "2025-03-06",
    customer: {
      name: "김지수",
      mobile: "010-1245-1534",
      email: "김지수@bingfree.co.kr",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
      shop: "personal",
    },
    membership: {
      name: null,
      date: null,
      count: null,
      during: null,
    },
    worker: {
      bingnb: "bing14",
      star: "4.5점(9개 리뷰)",
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "일회성 청소",
      machine: "[스탠다드] 50kg 미만 1대",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 4층",
      date: "2025.05.30",
      time: "오후 11시 이후",
      plus: "자가 점검 키트",
      memo: null,
    },
    payment: {
      service: 99000,
      extra: 4900,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
    },
    primemember: false,
  },
  {
    id: 15,
    number: "BING-2025-015",
    status: "assigned",
    date: "2025-02-15, 오후 3시 이후",
    memo: "레포트 문자로 보내주세요",
    price: 0,
    reservdate: "2025-02-26",
    customer: {
      name: "강다현",
      mobile: "010-1245-1534",
      email: "강다현@bingfree.co.kr",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
      shop: "business",
    },
    membership: {
      name: "스탠다드",
      package: "6회권",
      date: "2025-01-04 ~",
      count: "5회 / 6회",
      during: "2개월",
    },
    worker: {
      bingnb: "bing15",
      star: "4.5점(9개 리뷰)",
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "일회성 청소",
      machine: "[스탠다드] 50kg 미만 1대",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 4층",
      date: "2025-08-22",
      time: "오후 11시 이후",
      plus: null,
      memo: null,
    },
    payment: {
      service: 99000,
      extra: 0,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
    },
    primemember: true,
  },
  {
    id: 16,
    number: "BING-2025-016",
    status: "done", // (예시: 랜덤)
    date: "2025-02-15, 오후 3시 이후",
    memo: "레포트 받을래요~",
    price: 0,
    reservdate: "2025-02-20",
    customer: {
      name: "박소연",
      mobile: "010-7182-3345",
      email: "soyeon.park@bingfree.co.kr",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
      shop: "business",
    },
    membership: {
      name: "스탠다드",
      package: "6회권",
      date: "2025-01-04 ~",
      count: "5회 / 6회",
      during: "2개월",
    },
    worker: {
      bingnb: "bing16",
      number: "bing01",
      star: "4.5점(9개 리뷰)",
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "일회성 청소",
      machine: "[스탠다드] 50kg 미만 1대",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 4층",
      date: "2025-08-22",
      time: "오후 1시 이후",
      plus: null,
      memo: null,
    },
    payment: {
      service: 99000,
      extra: 0,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
    },
    primemember: false, // (예시: 랜덤)
  },

  // id: 17
  {
    id: 17,
    number: "BING-2025-017",
    status: "waiting", // (예시: 랜덤)
    date: "2025-02-15, 오후 3시 이후",
    memo: "레포트 받을래요~",
    price: 0,
    reservdate: "2025-02-20",
    customer: {
      name: "이정훈",
      mobile: "010-5923-1108",
      email: "junghoon.lee@bingfree.co.kr",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
      shop: "business",
    },
    membership: {
      name: "스탠다드",
      package: "6회권",
      date: "2025-01-04 ~",
      count: "5회 / 6회",
      during: "2개월",
    },
    worker: {
      bingnb: "bing17",
      star: "4.5점(9개 리뷰)",
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "일회성 청소",
      machine: "[스탠다드] 50kg 미만 1대",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 4층",
      date: "2025-08-22",
      time: "오후 11시 이후",
      plus: null,
      memo: null,
    },
    payment: {
      service: 99000,
      extra: 0,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
    },
    primemember: true, // (예시: 랜덤)
  },

  // id: 18
  {
    id: 18,
    number: "BING-2025-018",
    status: "confirmed", // (예시: 랜덤)
    date: "2025-02-15, 오후 3시 이후",
    memo: "레포트 받을래요~",
    price: 0,
    reservdate: "2025-02-20",
    customer: {
      name: "최민지",
      mobile: "010-8856-4401",
      email: "minji.choi@bingfree.co.kr",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
      shop: "business",
    },
    membership: {
      name: "스탠다드",
      package: "6회권",
      date: "2025-01-04 ~",
      count: "5회 / 6회",
      during: "2개월",
    },
    worker: {
      bingnb: "bing18",
      star: "4.5점(9개 리뷰)",
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "일회성 청소",
      machine: "[스탠다드] 50kg 미만 1대",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 4층",
      date: "2025-08-22",
      time: "오후 11시 이후",
      plus: null,
      memo: null,
    },
    payment: {
      service: 99000,
      extra: 0,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
    },
    primemember: false, // (예시: 랜덤)
  },

  // id: 19
  {
    id: 19,
    number: "BING-2025-019",
    status: "assigned", // (예시: 랜덤)
    date: "2025-02-15, 오후 3시 이후",
    memo: "레포트 받을래요~",
    price: 0,
    reservdate: "2025-02-20",
    customer: {
      name: "한지훈",
      mobile: "010-2334-9902",
      email: "jihoon.han@bingfree.co.kr",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
      shop: "business",
    },
    membership: {
      name: "스탠다드",
      package: "6회권",
      date: "2025-01-04 ~",
      count: "5회 / 6회",
      during: "2개월",
    },
    worker: {
      bingnb: "bing19",
      star: "4.5점(9개 리뷰)",
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "일회성 청소",
      machine: "[스탠다드] 50kg 미만 1대",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 4층",
      date: "2025-08-22",
      time: "오후 11시 이후",
      plus: null,
      memo: null,
    },
    payment: {
      service: 99000,
      extra: 0,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
    },
    primemember: true, // (예시: 랜덤)
  },

  // id: 20
  {
    id: 20,
    number: "BING-2025-020",
    status: "waiting", // (예시: 랜덤)
    date: "2025-02-15, 오후 3시 이후",
    memo: "레포트 받을래요~",
    price: 0,
    reservdate: "2025-02-20",
    customer: {
      name: "윤세영",
      mobile: "010-6667-2223",
      email: "seyoung.yoon@bingfree.co.kr",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
      shop: "business",
    },
    membership: {
      name: "스탠다드",
      package: "6회권",
      date: "2025-01-04 ~",
      count: "5회 / 6회",
      during: "2개월",
    },
    worker: {
      bingnb: "bing20",
      star: "4.5점(9개 리뷰)",
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "일회성 청소",
      machine: "[스탠다드] 50kg 미만 1대",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 4층",
      date: "2025-08-22",
      time: "오후 11시 이후",
      plus: null,
      memo: null,
    },
    payment: {
      service: 99000,
      extra: 0,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
    },
    primemember: false, // (예시: 랜덤)
  },
]);

// 지역 선택 데이터
export const koreaLocations = reactive({
  서울특별시: [
    "강남구",
    "강동구",
    "강북구",
    "강서구",
    "관악구",
    "광진구",
    "구로구",
    "금천구",
    "노원구",
    "도봉구",
    "동대문구",
    "동작구",
    "마포구",
    "서대문구",
    "서초구",
    "성동구",
    "성북구",
    "송파구",
    "양천구",
    "영등포구",
    "용산구",
    "은평구",
    "종로구",
    "중구",
    "중랑구",
  ],
  부산광역시: [
    "강서구",
    "금정구",
    "기장군",
    "남구",
    "동구",
    "동래구",
    "부산진구",
    "북구",
    "사상구",
    "사하구",
    "서구",
    "수영구",
    "연제구",
    "영도구",
    "중구",
    "해운대구",
  ],
  대구광역시: ["남구", "달서구", "달성군", "동구", "북구", "서구", "수성구", "중구"],
  인천광역시: ["강화군", "계양구", "남동구", "동구", "미추홀구", "부평구", "서구", "연수구", "옹진군", "중구"],
  광주광역시: ["광산구", "남구", "동구", "북구", "서구"],
  대전광역시: ["대덕구", "동구", "서구", "유성구", "중구"],
  울산광역시: ["남구", "동구", "북구", "울주군", "중구"],
  세종특별자치시: ["세종시"],
  경기도: [
    "가평군",
    "고양시",
    "과천시",
    "광명시",
    "광주시",
    "구리시",
    "군포시",
    "김포시",
    "남양주시",
    "동두천시",
    "부천시",
    "성남시",
    "수원시",
    "시흥시",
    "안산시",
    "안성시",
    "안양시",
    "양주시",
    "양평군",
    "여주시",
    "연천군",
    "오산시",
    "용인시",
    "의왕시",
    "의정부시",
    "이천시",
    "파주시",
    "평택시",
    "포천시",
    "하남시",
    "화성시",
  ],
  강원도: [
    "강릉시",
    "고성군",
    "동해시",
    "삼척시",
    "속초시",
    "양구군",
    "양양군",
    "영월군",
    "원주시",
    "인제군",
    "정선군",
    "철원군",
    "춘천시",
    "태백시",
    "평창군",
    "홍천군",
    "화천군",
    "횡성군",
  ],
  충청북도: [
    "괴산군",
    "단양군",
    "보은군",
    "영동군",
    "옥천군",
    "음성군",
    "제천시",
    "증평군",
    "진천군",
    "청주시",
    "충주시",
  ],
  충청남도: [
    "계룡시",
    "공주시",
    "금산군",
    "논산시",
    "당진시",
    "보령시",
    "부여군",
    "서산시",
    "서천군",
    "아산시",
    "예산군",
    "천안시",
    "청양군",
    "태안군",
    "홍성군",
  ],
  전라북도: [
    "고창군",
    "군산시",
    "김제시",
    "남원시",
    "무주군",
    "부안군",
    "순창군",
    "완주군",
    "익산시",
    "임실군",
    "장수군",
    "전주시",
    "정읍시",
    "진안군",
  ],
  전라남도: [
    "강진군",
    "고흥군",
    "곡성군",
    "광양시",
    "구례군",
    "나주시",
    "담양군",
    "목포시",
    "무안군",
    "보성군",
    "순천시",
    "신안군",
    "여수시",
    "영광군",
    "영암군",
    "완도군",
    "장성군",
    "장흥군",
    "진도군",
    "함평군",
    "해남군",
    "화순군",
  ],
  경상북도: [
    "경산시",
    "경주시",
    "고령군",
    "구미시",
    "군위군",
    "김천시",
    "문경시",
    "봉화군",
    "상주시",
    "성주군",
    "안동시",
    "영덕군",
    "영양군",
    "영주시",
    "영천시",
    "예천군",
    "울릉군",
    "울진군",
    "의성군",
    "청도군",
    "청송군",
    "칠곡군",
    "포항시",
  ],
  경상남도: [
    "거제시",
    "거창군",
    "고성군",
    "김해시",
    "남해군",
    "밀양시",
    "사천시",
    "산청군",
    "양산시",
    "의령군",
    "진주시",
    "창녕군",
    "창원시",
    "통영시",
    "하동군",
    "함안군",
    "함양군",
    "합천군",
  ],
  제주특별자치도: ["서귀포시", "제주시"],
});

// 테이블 헤더 데이터
export const TableHeaders = [
  { key: "item", label: "결제 내역" },
  { key: "amount", label: "결제금액" },
  { key: "date", label: "결제일" },
  { key: "period", label: "이용 기간" },
  { key: "status", label: "상태" },
  { key: "receipt", label: "영수증" },
];

// 테이블 내용 데이터
export const TableData = [
  {
    item: "호시자키(250kg~) 6회권",
    amount: "1,134,000원",
    date: "2025.03.17 14:00",
    period: "2025.03.17 ~ 2026.03.17",
    status: "결제 완료",
    receipt: "영수증 보기",
    receiptUrl: "#",
  },
];

// 클레임 내용 데이터
export const fullclaimList = reactive([
  {
    id: 1,
    number: "1",
    status: "confirmed",
    date: "2025-03-18",
    claimdate: "2025.03.21",
    memo: "라벨 부착해주세요.",
    price: 0,
    store: "사업자 ",
    customer: {
      name: "고윤정",
      claimId: "CLM250501",
      detailclaim: "서비스 품질",
      email: "yunjung@naver.com",
      mobile: "010-1451-1234",
      csSencitive: "신규/초회",
      avatar: "/prime/cs_first.png",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
    },
    membership: {
      name: "호시자키",
      package: "6회권",
      date: "2025-03-17 ~",
      count: "2회 / 6회",
      during: "3개월",
    },
    worker: {
      star: "4.5점(9개 리뷰)",
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
      gender: "female",
      health: false,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: "기타 문의",
      title: "라벨 증정",
      memo: "라벨 안 주고 가셨어요 ㅠㅠ",
      file: null,
    },
    reservinfo: {
      type: "서비스 품질",
      machine: "신규/초회",
      address: "c/s이력 없음",

      date: "2025.03.21",
      plus: "자가점검키트",
      memo: "청소 후 냄새 남음. 고객 불만 높음. 5/16 재방문 요청됨.",
    },
    payment: {
      service: 210000,
      extra: 4900,
      coupon: 0,
      membershipDiscount: -210000,
      extraDiscount: -4900,
    },
    primemember: true,
  },
  {
    id: 2,
    number: "2",
    status: "waiting",
    date: "2025-06-18",
    claimdate: "2025.06.21",
    memo: "세제 신청했어요 ~ ^^",
    price: 0,
    store: "사업자",
    customer: {
      name: "김카페",
      claimId: "CLM250401",
      detailclaim: "시간 관련",
      email: "cafekim@naver.com",
      mobile: "010-1431-4141",
      csSencitive: "주의고객",
      avatar: "/prime/cs_second.png",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
      shop: "personal",
      date: "2025-02-04",
    },
    membership: {
      name: null,
      date: null,
      count: null,
      during: null,
    },
    worker: {
      star: "4.5점(9개 리뷰)",
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "시간 관련",
      machine: "주의고객",
      address: "c/s이력 없음",

      date: "2025.06.21",
      plus: "자가점검키트",
      memo: "예약 시간보다 30분 늦게 도착. 고객 대기 불만 표출됨. 다음 방문 시 시간 엄수 필요.",
    },
    payment: {
      service: 99000,
      extra: 4900,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
    },
    primemember: false,
  },
  {
    id: 3,
    number: "3",
    status: "assigned",
    date: "2025-05-15",
    claimdate: "2025.05.21",
    memo: "레포트 문자로 보내주세요",
    price: 0,
    store: "사업자",
    customer: {
      name: "김카페",
      claimId: "CLM250515",
      detailclaim: "서비스 품질",
      mobile: "010-1245-1534",
      csSencitive: "민감고객",
      avatar: "/prime/cs_third.png",
      email: "cafekim@naver.com",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
      shop: "personal",
    },
    membership: {
      name: null,
      date: null,
      count: null,
      during: null,
    },
    worker: {
      star: "4.5점(9개 리뷰)",
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "서비스 품질",
      machine: "민감고객",
      address: "c/s이력 있음",

      date: "2025.04.21",
      plus: "자가점검키트",
      memo: "청소 후 얼음 색상과 맛 변화 없음. 효과에 대한 의구심 제기됨.",
    },
    payment: {
      service: 99000,
      extra: 0,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
    },
    primemember: false,
  },
  {
    id: 4,
    number: "4",
    status: "done",
    date: "2025-03-28",
    claimdate: "2025.03.28",
    memo: "라벨 부착해주세요.",
    price: 0,
    reservdate: "2025-05-28",
    store: "사업자 ",
    customer: {
      name: "정유진",
      claimId: "CLM250328",
      detailclaim: "응대/매너",
      mobile: "010-1234-1234",
      csSencitive: "고위험고객",
      avatar: "/prime/cs_fourd.png",
      email: "정유진@bingfree.co.kr",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
      shop: "personal",
    },
    membership: {
      name: "스탠다드",
      package: "6회권",
      date: "2025-01-25 ~",
      count: "3회 / 6회",
      during: "1개월",
    },
    worker: {
      star: "4.5점(9개 리뷰)",
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: "기타 문의",
      title: "라벨 증정",
      memo: "라벨 안 주고 가셨어요 ㅠㅠ",
      file: null,
    },
    reservinfo: {
      type: "응대/매너",
      machine: "고위험고객",
      address: "c/s이력 있음",

      date: "2025-04-18 , 2025-05-28 ",
      plus: "자가점검키트",
      memo: "방문 기사 응대 태도 관련 불만 제기. 말투와 설명 부족함 언급됨. 교육 필요 요청.",
    },
    payment: {
      service: 210000,
      extra: 4900,
      coupon: 0,
      membershipDiscount: -210000,
      extraDiscount: -4900,
    },
    primemember: true,
  },
  {
    id: 5,
    number: "5",
    status: "waiting",
    date: "2025-01-29",
    claimdate: "2025.01.21",
    memo: "세제 신청했어요 ~ ^^",
    price: 0,
    store: "개인",
    reservdate: "2025-02-21",
    customer: {
      name: "박서준",
      claimId: "CLM250129",
      detailclaim: "요금/결제",
      mobile: "010-1245-1534",
      csSencitive: "신규/초회",
      avatar: "/prime/cs_first.png",
      email: "박서준@bingfree.co.kr",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
      shop: "personal",
    },
    membership: {
      name: null,
      date: null,
      count: null,
      during: null,
    },
    worker: {
      star: "4.5점(9개 리뷰)",
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "요금/결제",
      machine: "신규/초회",
      address: "c/s이력 없음",

      date: "",
      plus: "자가점검키트",
      memo: "청소 구독 혜택이 제대로 적용되지 않음. 차액 환불 요청 있음.",
    },
    payment: {
      service: 99000,
      extra: 4900,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
    },
    primemember: false,
  },
  {
    id: 6,
    number: "6",
    status: "done",
    date: "2025-02-22",
    claimdate: "2025.02.24",
    memo: "레포트 문자로 보내주세요",
    price: 0,
    store: "개인 ",
    customer: {
      name: "최지은",
      claimId: "CLM250222",
      detailclaim: "예약/시스템",
      mobile: "010-1245-1534",
      email: "최지은@bingfree.co.kr",
      csSencitive: "신규/초회",
      avatar: "/prime/cs_first.png",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
      shop: "personal",
    },
    membership: {
      name: null,
      date: null,
      count: null,
      during: null,
    },
    worker: {
      star: "4.5점(9개 리뷰)",
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "예약/시스템",
      machine: "신규/초회",
      address: "c/s이력 없음",

      date: "",
      plus: "자가점검키트",
      memo: "예약 변경이 반영되지 않아 기사 잘못 방문. 고객 불쾌감 표시.",
    },
    payment: {
      service: 99000,
      extra: 0,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
    },
    primemember: false,
  },
  {
    id: 7,
    number: "7",
    status: "confirmed",
    date: "2025-02-12",
    claimdate: "2025.02.21",
    memo: "라벨 부착해주세요.",
    price: 0,
    store: "사업자",
    customer: {
      name: "이동건",
      claimId: "CLM250212",
      detailclaim: "기타",
      mobile: "010-1234-1234",
      email: "이동건@bingfree.co.kr",
      csSencitive: "신규/초회",
      avatar: "/prime/cs_first.png",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
      shop: "business",
    },
    membership: {
      name: "스탠다드",
      package: "12회권",
      date: "2025-01-26 ~",
      count: "5회 / 6회",
      during: "3개월",
    },
    worker: {
      star: "4.5점(9개 리뷰)",
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: "기타 문의",
      title: "라벨 증정",
      memo: "라벨 안 주고 가셨어요 ㅠㅠ",
      file: null,
    },
    reservinfo: {
      type: "기타",
      machine: "신규/초회",
      address: "c/s이력 없음",

      date: "",
      plus: "자가점검키트",
      memo: "매장 내 전기 미사용 가능 시간으로 청소 중단됨. 운영팀과 조율 요청됨.",
    },
    payment: {
      service: 210000,
      extra: 4900,
      coupon: 0,
      membershipDiscount: -210000,
      extraDiscount: -4900,
    },
    primemember: true,
  },
  {
    id: 8,
    number: "8",
    status: "waiting",
    date: "2025-01-05",
    claimdate: "2025.01.07",
    memo: "세제 신청했어요 ~ ^^",
    price: 0,
    store: "개인",
    customer: {
      name: "장민호",
      claimId: "CLM250105",
      detailclaim: "시간 관련",
      mobile: "010-1245-1534",
      csSencitive: "민감고객",
      avatar: "/prime/cs_second.png",
      email: "장민호@bingfree.co.kr",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
      shop: "business",
    },
    membership: {
      name: "스탠다드",
      package: "12회권",
      date: "2025-03-13 ~",
      count: "3회 / 6회",
      during: "6개월",
    },
    worker: {
      star: "4.5점(9개 리뷰)",
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "시간 관련",
      machine: "민감고객",
      address: "c/s이력 있음",

      date: "2025.01.07",
      plus: "자가점검키트",
      memo: "일정 사전 고지 없이 시간 변경되어 고객 혼선 발생. 불만 접수됨.",
    },
    payment: {
      service: 99000,
      extra: 4900,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
    },
    primemember: true,
  },
  {
    id: 9,
    number: "9",
    status: "done",
    date: "2025-02-09",
    claimdate: "2025.02.21",
    memo: "레포트 문자로 보내주세요",
    price: 0,
    reservdate: "2025-02-19",
    store: "개인 ",
    customer: {
      name: "하윤아",
      claimId: "CLM250221",
      detailclaim: "기타",
      mobile: "010-1245-1534",
      csSencitive: "민감고객",
      avatar: "/prime/cs_third.png",
      email: "하윤아@bingfree.co.kr",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
      shop: "personal",
    },
    membership: {
      name: null,
      date: null,
      count: null,
      during: null,
    },
    worker: {
      star: "4.5점(9개 리뷰)",
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "기타",
      machine: "민감고객",
      address: "c/s이력 있음",

      date: "2025-02-19",
      plus: "자가점검키트",
      memo: "현장 접근 어려움(지하 창고)으로 장비 운반 지연 발생. 사전 안내 필요.",
    },
    payment: {
      service: 99000,
      extra: 0,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
    },
    primemember: false,
  },
  {
    id: 10,
    number: "10",
    status: "confirmed",
    date: "2025-03-26",
    claimdate: "2025.03.27",
    memo: "라벨 부착해주세요.",
    price: 0,
    store: "사업자 ",
    customer: {
      name: "문채원",
      claimId: "CLM250326",
      detailclaim: "응대/매너",
      mobile: "010-1234-1234",
      csSencitive: "신규/초회",
      avatar: "/prime/cs_first.png",
      email: "문채원@bingfree.co.kr",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
      shop: "business",
    },
    membership: {
      name: "스탠다드",
      package: "6회권",
      date: "2025-01-22 ~",
      count: "6회 / 6회",
      during: "3개월",
    },
    worker: {
      star: "4.5점(9개 리뷰)",
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: "기타 문의",
      title: "라벨 증정",
      memo: "라벨 안 주고 가셨어요 ㅠㅠ",
      file: null,
    },
    reservinfo: {
      type: "응대/매너",
      machine: "신규/초회",
      address: "c/s이력 없음",

      date: "",
      plus: "자가점검키트",
      memo: "고객 질문에 무성의한 대응으로 신뢰도 하락. 정중한 응대 요청됨.",
    },
    payment: {
      service: 210000,
      extra: 4900,
      coupon: 0,
      membershipDiscount: -210000,
      extraDiscount: -4900,
    },
    primemember: true,
  },
  {
    id: 11,
    number: "11",
    status: "waiting",
    date: "2025-01-27",
    claimdate: "2025.01.29",
    memo: "세제 신청했어요 ~ ^^",
    price: 0,
    store: "사업자 ",
    customer: {
      name: "윤도현",
      claimId: "CLM250127",
      detailclaim: "시간 관련",
      mobile: "010-1245-1534",
      csSencitive: "민감고객",
      avatar: "/prime/cs_second.png",
      email: "윤도현@bingfree.co.kr",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
      shop: "business",
    },
    membership: {
      name: "스탠다드",
      package: "6회권",
      date: "2025-02-04 ~",
      count: "3회 / 6회",
      during: "1개월",
    },
    worker: {
      star: "4.5점(9개 리뷰)",
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "시간 관련",
      machine: "민감고객",
      address: "c/s이력 있음",

      date: "2025.01.29",
      plus: "자가점검키트",
      memo: "기사 도착 전 연락 없었음. 고객 당황하며 재방문 요구함.",
    },
    payment: {
      service: 99000,
      extra: 4900,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
    },
    primemember: true,
  },
  {
    id: 12,
    number: "12",
    status: "assigned",
    date: "2025-01-20",
    claimdate: "2025.01.21",
    memo: "레포트 문자로 보내주세요",
    price: 0,
    reservdate: "2025-08-27",
    store: "개인 ",
    customer: {
      name: "백예린",
      claimId: "CLM250120",
      detailclaim: "요금/결제",
      mobile: "010-1245-1534",
      email: "백예린@bingfree.co.kr",
      csSencitive: "신규/초회",
      avatar: "/prime/cs_first.png",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
      shop: "personal",
    },
    membership: {
      name: null,
      date: null,
      count: null,
      during: null,
    },
    worker: {
      star: "4.5점(9개 리뷰)",
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "요금/결제",
      machine: "신규/초회",
      address: "c/s이력 없음",

      date: "",
      plus: "자가점검키트",
      memo: "추가 비용 발생 안내 미흡으로 고객 오해 발생. 정확한 요금 안내 요청함.",
    },
    payment: {
      service: 99000,
      extra: 0,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
    },
    primemember: false,
  },
  {
    id: 13,
    number: "13",
    status: "confirmed",
    date: "2025-01-09",
    claimdate: "2025.01.11",
    memo: "라벨 부착해주세요.",
    price: 0,
    store: "사업자 ",
    customer: {
      name: "서지호",
      claimId: "CLM250109",
      detailclaim: "서비스 품질",
      mobile: "010-1234-1234",
      email: "서지호@bingfree.co.kr",
      csSencitive: "주의고객",
      avatar: "/prime/cs_third.png",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
      shop: "business",
    },
    membership: {
      name: "스탠다드",
      package: "12회권",
      date: "2025-03-09 ~",
      count: "1회 / 6회",
      during: "3개월",
    },
    worker: {
      star: "4.5점(9개 리뷰)",
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: "기타 문의",
      title: "라벨 증정",
      memo: "라벨 안 주고 가셨어요 ㅠㅠ",
      file: null,
    },
    reservinfo: {
      type: "서비스 품질",
      machine: "주의고객",
      address: "c/s이력 있음",

      date: "2025.01.11",
      plus: "자가점검키트",
      memo: "얼음 저장고 내부 세척 누락 발견. 현장 확인 요청됨.",
    },
    payment: {
      service: 210000,
      extra: 4900,
      coupon: 0,
      membershipDiscount: -210000,
      extraDiscount: -4900,
    },
    primemember: true,
  },
  {
    id: 14,
    number: "14",
    status: "waiting",
    date: "2025-01-18",
    claimdate: "2025.01.21",
    memo: "세제 신청했어요 ~ ^^",
    price: 0,
    store: "개인 ",
    customer: {
      name: "김지수",
      claimId: "CLM250118",
      detailclaim: "시간 관련",
      mobile: "010-1245-1534",
      csSencitive: "신규/초회",
      avatar: "/prime/cs_first.png",
      email: "김지수@bingfree.co.kr",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
      shop: "personal",
    },
    membership: {
      name: null,
      date: null,
      count: null,
      during: null,
    },
    worker: {
      star: "4.5점(9개 리뷰)",
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "시간 관련",
      machine: "신규/초회",
      address: "c/s이력 없음",

      date: "",
      plus: "자가점검키트",
      memo: "일정 사전 고지 없이 시간 변경되어 고객 혼선 발생. 불만 접수됨.",
    },
    payment: {
      service: 99000,
      extra: 4900,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
    },
    primemember: false,
  },
  {
    id: 15,
    number: "15",
    status: "assigned",
    date: "2025-02-15",
    claimdate: "2025.02.21",
    memo: "레포트 문자로 보내주세요",
    price: 0,
    store: "사업자 ",
    customer: {
      name: "강다현",
      mobile: "010-1245-1534",
      claimId: "CLM250221",
      detailclaim: "서비스 품질",
      email: "강다현@bingfree.co.kr",
      csSencitive: "민감고객",
      avatar: "/prime/cs_second.png",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
      shop: "business",
    },
    membership: {
      name: "스탠다드",
      package: "6회권",
      date: "2025-01-04 ~",
      count: "5회 / 6회",
      during: "2개월",
    },
    worker: {
      star: "4.5점(9개 리뷰)",
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
      gender: "male",
      health: true,
      location: {
        서울특별시: ["강남구", "마포구"],
      },
      bank: "국민은행",
      account: "620002-04-218816",
      during: "1개월",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "서비스 품질",
      machine: "민감고객",
      address: "c/s이력 있음",

      date: "2025.02.21",
      plus: "자가점검키트",
      memo: "필터 교체 후 기기 작동 불안정함. 서비스 품질 신뢰도 낮아짐.",
    },
    payment: {
      service: 99000,
      extra: 0,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
    },
    primemember: true,
  },
]);
